### ISSUE TITLE
Release Android v5.1.4

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10065]
# Android v5.1.4
We are releasing the fourth patch release on top of the v5.1.0 version of the Android SDK. This release adds the bugfixes mentioned below. Feel free to report any feedback you have on this release [here](https://github.com/mapbox/mapbox-gl-native/issues).

## Changes since v5.1.3

* Update translations [#10033](https://github.com/mapbox/mapbox-gl-native/pull/10033) & [#9945](https://github.com/mapbox/mapbox-gl-native/pull/9945)
* Fix layer z-fighting [#9942](https://github.com/mapbox/mapbox-gl-native/pull/9942)
* Align line vertex to 4-byte boundary [#9943](https://github.com/mapbox/mapbox-gl-native/pull/9943)
* Bump proguard config for OkHttp [#9970](https://github.com/mapbox/mapbox-gl-native/pull/9970)
* Remove database on schema downgrade [#9837](https://github.com/mapbox/mapbox-gl-native/pull/9837)
* Disable rotation gesture when pinch zooming [#10026](https://github.com/mapbox/mapbox-gl-native/pull/10026)
* Do not check if connection is local request [#9968](https://github.com/mapbox/mapbox-gl-native/pull/9968)
* Harden offline region deletion [#9967](https://github.com/mapbox/mapbox-gl-native/pull/9967)
* Clear out mapCallback's OnMapReadyListeners on destroy [#9957](https://github.com/mapbox/mapbox-gl-native/pull/9957)
* Avoid adding duplicate points to bounds [#9955](https://github.com/mapbox/mapbox-gl-native/pull/9955)
* Continue rendering tiles despite errors [#10012](https://github.com/mapbox/mapbox-gl-native/pull/10012)
* Download is complete fix [#9913](https://github.com/mapbox/mapbox-gl-native/pull/9913)
* MAS 2.2.3 [#9901](https://github.com/mapbox/mapbox-gl-native/pull/9901)

## Todo

- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.1.4` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.1.4` artifact to Maven Central
- [x] Tag `android-v5.1.4` 
- [x] Change version name to `5.2.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.1.4` back into `release-ios-v3.6.0-android-v5.1.0`
- [x] Update Javadoc documentation @langsmith 
- [x] Update SDK version to `5.1.4` in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps to use `5.1.4` @langsmith 
- [x] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in [Store Locator kit](https://github.com/mapbox/store-locator-android)
- [x] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support

**Comment by tobrun** [comment]
Release if available on Maven [here](http://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/5.1.4/).

**Comment by Danny-James** [comment]
I've Just Updated My Gradle To Use This Version, Will Report Any Issues I Find. Many Thanks!

**Comment by tobrun** [comment]
I'm going a head and close this issue, will leave it up @langsmith to finish the two remaining items.
