### ISSUE TITLE
Release Android v5.1.5

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10331]
# Android v5.1.5
We are releasing the fifth patch release on top of the v5.1.0 version of the Android SDK. This release adds the bugfixes mentioned below. Feel free to report any feedback you have on this release [here](https://github.com/mapbox/mapbox-gl-native/issues).

## Changes since v5.1.4

* Determine need for clip ID based on actual layers/tiles [#10216](https://github.com/mapbox/mapbox-gl-native/pull/10216)
* Correctly alter sprite URLs [#10217](https://github.com/mapbox/mapbox-gl-native/pull/10217)
* Remove obsolete terminate context/display calls [#10162](https://github.com/mapbox/mapbox-gl-native/pull/10162)
* Russian and Ukrainian localizations [#9945](https://github.com/mapbox/mapbox-gl-native/pull/9945)

## Todo
 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.1.5` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.1.5` artifact to Maven Central
- [x] Tag `android-v5.1.5` 
- [x] Change version name to `5.2.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.1.5` back into `release-ios-v3.6.0-android-v5.1.0`
- [ ] Update Javadoc documentation @langsmith 
- [ ] Update SDK version to `5.1.5` in `android-docs` repo's `constants.js` file @langsmith 
- [ ] Update Mapbox demo and wearable demo apps to use `5.1.5` @langsmith 
- [ ] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [ ] Update version # in `config` files in /help @langsmith
- [ ] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] Update version # in [Store Locator kit](https://github.com/mapbox/store-locator-android)
- [x] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] Update version # in cn @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support

**Comment by langsmith** [comment]
5.1.5 javadocs have been added and I updated Fabric, but I'm going to leave /help , /www.mapbox.com, store locator kit, demo app, and cn with 5.2.0-beta.3 instead of switching them to 5.1.5 . This means that I consider my responsibilities on this ticket as complete. 

If you think they should go to 5.1.5, let me know. No problem and I'll update other repos.   

@tobrun @Guardiola31337 @zugaldia

**Comment by tobrun** [comment]
Thank you for running with that @langsmith, good to close here.
