### ISSUE TITLE
Release Android v5.2.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10646]
# Android v5.2.1
We are releasing the first patch release on top of the v5.2.0 version of the Android SDK. This release adds the bugfixes mentioned below. Feel free to report any feedback you have on this release [here](https://github.com/mapbox/mapbox-gl-native/issues).

## Changes since v5.2.0
 - Close race condition in RunLoop [#10537](https://github.com/mapbox/mapbox-gl-native/pull/10537)
 - OkHttp 3.9.1 [#10515](https://github.com/mapbox/mapbox-gl-native/pull/10515)
 - Attribution anchor point fix [#10558](https://github.com/mapbox/mapbox-gl-native/pull/10558)
 - Pre API 19 VerifyError [#10579](https://github.com/mapbox/mapbox-gl-native/pull/10579)
 - Set larger Http request limit [#10567](https://github.com/mapbox/mapbox-gl-native/pull/10567) 
 - Remove jar generation from maven publish [#10625](https://github.com/mapbox/mapbox-gl-native/pull/10625)
 - Enable Map Rendering when paused for multiple window support [#10509](https://github.com/mapbox/mapbox-gl-native/pull/10509)
 - Activate FileSource when listing offline regions [#10531](https://github.com/mapbox/mapbox-gl-native/pull/10531)
 - Harden MarkerView integration by checking for null bitmap [#10532](https://github.com/mapbox/mapbox-gl-native/pull/10532)
 - Use concurrent lists for camera change listeners [#10542](https://github.com/mapbox/mapbox-gl-native/pull/10542)
 - Handle destroy activity as part of theme switching [#10589](https://github.com/mapbox/mapbox-gl-native/pull/10589)
 - add FileSource activation/deactivation to MapSnapshotter [#10556](https://github.com/mapbox/mapbox-gl-native/pull/10556)

## Todo
 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.2.1` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [ ] Publish `5.2.1` artifact to Maven Central
- [x] Tag `android-v5.2.1` 
- [x] Change version name to `5.3.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.2.1` back into `release-ios-v3.6.0-android-v5.1.0`
- [x] Update Javadoc documentation @langsmith 
- [x] Update SDK version to `5.2.1` in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps to use `5.2.1` @langsmith 
- [x] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthf @langsmith
- [x] Update version # in [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [x] Update version # in cn @langsmith
- [x] Update version # in livewebinar @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support
