### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10719]
Feature request to allow setting the background of the render surface to transparent:

<img width="146" alt="screen shot 2017-12-12 at 16 08 08" src="https://user-images.githubusercontent.com/2151639/34072722-c9a1a348-e28c-11e7-8b22-6d1616380f7d.png">

Working branch [here](https://github.com/mapbox/mapbox-gl-native/tree/tvn-transparent-surface).

This feature allows to see through the map bounds and see items in the viewhierachy that are behind it (currently this shows a black background). Besides the feature request this also solves the issue of a flashing black background when starting up a mapview. 

There are a couple of ways that we could expose this an api:
  - expose the variables set with eglconfig chooser
  - more limited api with a togle for enabling the transparent background

Before implementing we need to identify what the performance impact will be and if this feature introduces any regressions on older OS verions.

cc @zugaldia @ericdeveloper @kalimar

**Comment by tobrun** [comment]
Was able to get something working with GLSurfaceView:
<img width="284" alt="screen shot 2017-12-18 at 15 55 57" src="https://user-images.githubusercontent.com/2151639/34112152-f7fc8f52-e40b-11e7-9a84-8aadbb6916af.png">

While it works, it also doesn't show our logo and attribution icon anymore. 
Going to see if I can make this work with TextureView.

**Comment by zugaldia** [comment]
> more limited api with a togle for enabling the transparent background

I like this approach, preferably being opt-in. This enables the usecase while minimizing potential side effects (rendering, or performance).

**Comment by tobrun** [comment]
To follow up on this, approach mentioned in https://github.com/mapbox/mapbox-gl-native/issues/10719#issuecomment-352448689 will not be feasible due to needing to move the surface before all the views in the hierarchy, as a result the logo/attribution/compass isn't showing anymore and this would go in against our terms and conditions. 

I'm looking now into if a TextureView approach is feasible (as this render component wouldn't require the same changes as GlSurfaceView). TBC.

**Comment by tobrun** [comment]
Got a POC working with TextureView:

### Before
<img width="143" alt="screen shot 2018-01-26 at 13 44 25" src="https://user-images.githubusercontent.com/2151639/35440319-29c14828-029f-11e8-9712-1805b318c711.png">



### After

<img width="143" alt="screen shot 2018-01-26 at 13 41 46" src="https://user-images.githubusercontent.com/2151639/35440322-2c55f926-029f-11e8-834b-4bfd1cca621b.png">

## TODO
 - [ ] determine performance impact
 - [ ] boil current configuration down to minimal changes
 - [ ] expose as a configurable

**Comment by tobrun** [comment]
## Render performance comparison:

### Before
![ezgif com-video-to-gif 35](https://user-images.githubusercontent.com/2151639/35442657-4fff49e6-02a8-11e8-913c-8c931650784f.gif)

### After
![ezgif com-video-to-gif 36](https://user-images.githubusercontent.com/2151639/35442665-5796cd00-02a8-11e8-9de8-30c876d102da.gif)

There is no concrete indication that a translucent surface is adding performance overhead.

**Comment by tobrun** [comment]
This landed with #11065
