### ISSUE TITLE
Release Android v5.3.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10757]
Today we are releasing Android v5.3.0, which builds further on 5.2.0, adds the following support for TInySDF and multiple bugfixes. Feel free to report any feedback you have on this release [here](https://github.com/mapbox/mapbox-gl-native/issues).

### Changes since v5.2.0
  - Add support for TinySDF [#10706](https://github.com/mapbox/mapbox-gl-native/pull/10706)
  - Save restore MyLocationViewSettings [#10746](https://github.com/mapbox/mapbox-gl-native/pull/10746) 
 - Post animation callback invocation [#10664](https://github.com/mapbox/mapbox-gl-native/pull/10664).
  - Allow configuring Http logging [#10681](https://github.com/mapbox/mapbox-gl-native/pull/10681).
  - Fix reverse scale gesture [#10688](https://github.com/mapbox/mapbox-gl-native/pull/10688)
  - Update offline region metadata documentation [#10693](https://github.com/mapbox/mapbox-gl-native/pull/10693)
  - Post camera listener invocation [#10690](https://github.com/mapbox/mapbox-gl-native/pull/10690)
  - Activate filesource for offline region creation [#10718](https://github.com/mapbox/mapbox-gl-native/pull/10718)
  - Update Spanish/Vietnamese translations [#10740](https://github.com/mapbox/mapbox-gl-native/pull/10740)
  - Update instrumented make target [#10724](https://github.com/mapbox/mapbox-gl-native/pull/10724)
  - Remove black flash on start for fragments [#10717](https://github.com/mapbox/mapbox-gl-native/pull/10717).
  - CompassView decode crash [#10717](https://github.com/mapbox/mapbox-gl-native/pull/10717)
  - Android SDK renaming [#10609](https://github.com/mapbox/mapbox-gl-native/pull/10609)
  - Map touch listener based lists [#10749](https://github.com/mapbox/mapbox-gl-native/pull/10749)

### Todo
 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.3.0` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.3.0` artifact to Maven Central
- [x] Tag `android-v5.3.0` 
- [x] Change version name to `5.3.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.3.0` back into `release-agua`
- [ ] Update Javadoc documentation @langsmith 
- [ ] Update SDK version to `5.3.0` in `android-docs` repo's `constants.js` file @langsmith 
- [ ] Update Mapbox demo and wearable demo apps to use `5.3.0` @langsmith 
- [ ] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [ ] Update version # in `config` files in /help @langsmith
- [ ] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] Update version # in pthf @langsmith
- [ ] Update version # in [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [ ] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] Update version # in cn @langsmith
- [ ] Update version # in livewebinar @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support
