### ISSUE TITLE
Release Android v5.3.1 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10886]
Today we are releasing Android v5.3.1. This release builds further on v5.3.0 and adds support for RTL and multiple bugfixes. Feel free to report any feedback you have on this release here.

### Changes since v5.3.0
 - Blacklist binary program loading for Vivante GC4000 GPUs [#10862](https://github.com/mapbox/mapbox-gl-native/pull/10862)
 - Support Genymotion [#10841](https://github.com/mapbox/mapbox-gl-native/pull/10841)
 - Getting bitmap from drawable fix [#10763](https://github.com/mapbox/mapbox-gl-native/pull/10763)
 - Use US locale when converting between int color and RGBA string [#10810](https://github.com/mapbox/mapbox-gl-native/pull/10810)
 - Harden map destruction [#10811](https://github.com/mapbox/mapbox-gl-native/pull/10811)
 - RTL support [#10828](https://github.com/mapbox/mapbox-gl-native/pull/10828)
 - Allow configuring Http url logging when a request fails [#10830](https://github.com/mapbox/mapbox-gl-native/pull/10830)
 - Don't send double tap event multiple times for telemetry [#10854](https://github.com/mapbox/mapbox-gl-native/pull/10854)
 - Use the correct cancelable callback after posting cancel [#10871](https://github.com/mapbox/mapbox-gl-native/pull/10871) 

### Todo
 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.3.1` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.3.1` artifact to Maven Central
- [x] Tag `android-v5.3.1` 
- [x] Change version name to `5.3.2-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.3.1` back into `release-agua`
- [x] Update Javadoc documentation @langsmith 
- [x] Update SDK version to `5.3.1` in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps to use `5.3.1` @langsmith 
- [x] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [x] Update version # in [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [x] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [x] Update version # in cnplgn @langsmith
- [x] Update version # in cndocs @langsmith
- [x] Update version # in livewebinar @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support
