### ISSUE TITLE
Release Android v5.3.2

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10988]
### Changes since v5.3.1
 - Validate surface creation before destroying [#10890](https://github.com/mapbox/mapbox-gl-native/pull/10890)
 - Add filesource activation to OfflineRegion [#10904](https://github.com/mapbox/mapbox-gl-native/pull/10904)
 - Save configuration of UiSettings [#10908](https://github.com/mapbox/mapbox-gl-native/pull/10908)
 - Do not overwrite user-set focal point [#10910](https://github.com/mapbox/mapbox-gl-native/pull/10910)
 - Camera callbacks for velocity animated movements [#10925](https://github.com/mapbox/mapbox-gl-native/pull/10925)
 - Allow changing the used OkHttpClient [#10948](https://github.com/mapbox/mapbox-gl-native/pull/10948)
 - Validate zoom level before creating telemetry event [#10959](https://github.com/mapbox/mapbox-gl-native/pull/10959)
 - Handle null call instances in HttpRequest [#10987](https://github.com/mapbox/mapbox-gl-native/pull/10987)

### Todo
 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.3.2` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.3.2` artifact to Maven Central
- [x] Tag `android-v5.3.2` 
- [x] Change version name to `5.3.3-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [ ] Merge `release-android-v5.3.2` back into `release-agua`
- [x] Update Javadoc documentation via release branch, _not_ `master` @langsmith 
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps @langsmith 
- [x] If stable version, update `mapbox-plugins-android` test app @langsmith 
- [x] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [x] Update version # in [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [x] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [x] Update version # in cnplgn @langsmith
- [x] Update version # in cndocs @langsmith
- [x] @colleenmcginnis 

--------------------------
/cc @mapbox/mobile @mapbox/support

**Comment by tobrun** [comment]
I'm closing this issue as we are releasing v6.0.0-beta.1

cc @zugaldia
