### ISSUE TITLE
Implement all built-in NSExpression functions

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11059]
The NSExpression-based property value implementation in #10726 doesn’t support all [the functions built into NSExpression](https://developer.apple.com/documentation/foundation/nsexpression/1413747-init#discussion). This is a master ticket tracking the remaining unimplemented functions:

* [ ] `median:`: mapbox/mapbox-gl-js#5853
* [ ] `mode:`: mapbox/mapbox-gl-js#5853
* [ ] `stddev:`: mapbox/mapbox-gl-js#5853
* [ ] `random`: mapbox/mapbox-gl-js#5853 (unlikely)
* [ ] `randomn:`: mapbox/mapbox-gl-js#5853 (unlikely)
* [ ] `now`
* [ ] `bitwiseAnd:with:` (would conflict with #11053)
* [ ] `bitwiseOr:with:`
* [ ] `bitwiseXor:with:`
* [ ] `leftshift:by:`
* [ ] `rightshift:by:`
* [ ] `onesComplement:`
* [ ] `distanceToLocation:fromLocation:`: mapbox/mapbox-gl-js#6062

/cc @anandthakker
