### ISSUE TITLE
Release Android v6.0.0-beta.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11060]
In preparation for release v6.0.0 of the Mapbox Android SDK, we're releasing today the first beta in the 6.0.x series. This release brings major features as:
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection

![device-2018-01-25-104814](https://user-images.githubusercontent.com/2151639/35433566-3bafe05a-0284-11e8-8e5d-000dd9301ab1.png)

Please note that this is a pre-release version intended to gather early feedback on the new APIs and to detect any potential issues (you can report them [here](https://github.com/mapbox/mapbox-gl-native/issues)). This release is not intended for production apps.

### Changes since v5.x
 - Binding integration for expressions [#10654](https://github.com/mapbox/mapbox-gl-native/pull/10654)
 - CustomGeometrySource [#9983](https://github.com/mapbox/mapbox-gl-native/pull/9983)
 - HillshadeLayer and RasterDemSource [#11031](https://github.com/mapbox/mapbox-gl-native/pull/11031)
 - Revisit marker placement for snapshot [#11029](https://github.com/mapbox/mapbox-gl-native/pull/11029)
 - SafeVarargs annotation for expressions [#11027](https://github.com/mapbox/mapbox-gl-native/pull/11027)
 - Expression#toString [#11024](https://github.com/mapbox/mapbox-gl-native/pull/11024)
 - Rename initRenderSurface to onSurfaceCreated [#11023](https://github.com/mapbox/mapbox-gl-native/pull/11023)
 - Expose attribution manager as public API [#10942](https://github.com/mapbox/mapbox-gl-native/pull/10942)
 - Replace Mapzen vector source example with Mapillary [#10931](https://github.com/mapbox/mapbox-gl-native/pull/10931)
 - Add Hebrew localization [#10967](https://github.com/mapbox/mapbox-gl-native/pull/10967)
 - Cleanup gradle configuration files [#10903](https://github.com/mapbox/mapbox-gl-native/pull/10903)
 - Send double tap event only once [#10855](https://github.com/mapbox/mapbox-gl-native/pull/10855)
 - Parameter validation for LatLngBounds#from [#10831](https://github.com/mapbox/mapbox-gl-native/pull/10831)
 - Replace JSON parsing [#10815](https://github.com/mapbox/mapbox-gl-native/pull/10815)
 - Orientation change regression test [#10814](https://github.com/mapbox/mapbox-gl-native/pull/10814)
 - Max & min LatLng constants [#10780](https://github.com/mapbox/mapbox-gl-native/pull/10780)
 - LatLng#wrap return new instance of LatLng [#10769](https://github.com/mapbox/mapbox-gl-native/pull/10769)
 - Custom library loader [#10733](https://github.com/mapbox/mapbox-gl-native/pull/10733)
 - Inconsistent parameters for LatLngBounds.union [#10728](https://github.com/mapbox/mapbox-gl-native/pull/10728)
 - Gradle 4.1 / AS 3.0 [#10549](https://github.com/mapbox/mapbox-gl-native/pull/10549)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.0.0-beta.1` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.0.0-beta.1` artifact to Maven Central
- [x] Tag `android-v6.0.0-beta.1` 
- [x] Change version name to `6.0.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.0.0-beta.1` back into `release-boba`
- [x] Update Javadoc documentation via release branch, _not_ `master` @langsmith 
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [ ] Update Mapbox demo and wearable demo apps @langsmith 
- [ ] ~~If stable version, update `mapbox-plugins-android` test app @langsmith~~ 
- [ ] TBD: update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)
- [x] Update version # in `config` files in /help @langsmith
- [ ] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] Update version # in pthfndr @langsmith
- [ ] Update version # in Studio Preview @langsmith
- [ ] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] ~~If not beta release, update version # in cnplgn @langsmith~~
- [x] Update version # in cndocs @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by zugaldia** [comment]
Please note that due to a change in how Gradle manages dependencies in the latest version, there's a change on how to include this SDK on a `build.gradle` file. Explanation and workaround is available on https://github.com/mapbox/mapbox-gl-native/issues/11125#issuecomment-363698079. A fix for this is expected before the final 6.0 release.
