### ISSUE TITLE
Release Android v5.4.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11098]
Today we release the 5.4.0 version of the Mapbox Maps SDK for Android.

### Changes since v5.3.2
 - Blacklist Adreno 2xx GPU for VAO support [#11047](https://github.com/mapbox/mapbox-gl-native/pull/11047)
 - Bearing tracking mode GPS_NORTH_FACING [#11095](https://github.com/mapbox/mapbox-gl-native/pull/11095)
 - Disable logging missing location permissons [#11084](https://github.com/mapbox/mapbox-gl-native/pull/11084)
 - Create offline handler using the main thread looper [#11021](https://github.com/mapbox/mapbox-gl-native/pull/11021)
 
### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.4.0` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.4.0` artifact to Maven Central
- [x] Tag `android-v5.4.0` 
- [x] Change version name to `5.4.1-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [ ] Merge `release-android-v5.4.0` back into `release-agua`
- [ ] Update Javadoc documentation via release branch, _not_ `master` @langsmith 
- [ ] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [ ] Update Mapbox demo and wearable demo apps @langsmith 
- [ ] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [ ] Update version # in `config` files in /help @langsmith
- [ ] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] Update version # in pthfndr @langsmith
- [ ] Update version # in Studio Preview @langsmith
- [x] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] ~~If not beta release, update version # in cnplgn @langsmith~~
- [ ] Update version # in cndocs @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis
