### ISSUE TITLE
Release Android v5.4.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11162]
Today we release the 5.4.1 version of the Mapbox Maps SDK for Android.

### Changes since v5.4.0
 - Don't recreate TextureView surface as part of view resizing, solves OOM crashes [#11148](https://github.com/mapbox/mapbox-gl-native/pull/11148)
 - Don't invoke OnLowMemory before map is ready, solves crash on low memory devices [#11109](https://github.com/mapbox/mapbox-gl-native/pull/11109)
 - Programmatically create GLSurfaceView, solves fragment bug [#11124](https://github.com/mapbox/mapbox-gl-native/pull/11124)
 - Proguard config for optional location provider, solves obfuscation warnings [#11127](https://github.com/mapbox/mapbox-gl-native/pull/11127)
 - MapView weak reference in global layout listener, solves memory leak [#11128](https://github.com/mapbox/mapbox-gl-native/pull/11128)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.4.1` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.4.1` artifact to Maven Central
- [x] Tag `android-v5.4.1` 
- [x] Change version name to `5.4.2-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [ ] Merge `release-android-v5.4.1` back into `release-agua`
- [x] Update Javadoc documentation via release branch, _not_ `master` @langsmith 
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps @langsmith
- [x] Update version # in [`mapbox-navigation-android`](https://github.com/mapbox/mapbox-navigation-android/blob/master/gradle/dependencies.gradle) @langsmith
- [ ] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [ ] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [ ] Update version # in Studio Preview @langsmith
- [x] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] ~~If not beta release, update version # in cnplgn @langsmith~~
- [x] Update version # in cndocs @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis
