### ISSUE TITLE
Release Android v6.0.0-beta.2

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11188]
In preparation for release v6.0.0 of the Mapbox Android SDK, we're releasing today the second beta in the 6.0.x series. The 6.x release brings major features as:
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection
 - Transparent TextureView

![device-2018-01-25-104814](https://user-images.githubusercontent.com/2151639/35433566-3bafe05a-0284-11e8-8e5d-000dd9301ab1.png)

Please note that this is a pre-release version intended to gather early feedback on the new APIs and to detect any potential issues (you can report them [here](https://github.com/mapbox/mapbox-gl-native/issues)). This release is not intended for production apps.

### Changes since v6.0.0-beta.1 
 - Deprecate LocationEngine [#11185](https://github.com/mapbox/mapbox-gl-native/pull/11185)
 - Remove LOST from SDK [11186](https://github.com/mapbox/mapbox-gl-native/pull/11186)
 - Transparent surface configuration on TextureView [#11065](https://github.com/mapbox/mapbox-gl-native/pull/11065)
 - Constrained setLatLng documentation, expose setLatLngZoom method [#11184](https://github.com/mapbox/mapbox-gl-native/pull/11184)
 - Integration of new events library [#10999](https://github.com/mapbox/mapbox-gl-native/pull/10999)
 - AddImage performance improvement [#11111](https://github.com/mapbox/mapbox-gl-native/pull/11111)
 - Migrate MAS to 3.0.0, refactor GeoJson integration [#11149](https://github.com/mapbox/mapbox-gl-native/pull/11149)
 - Remove jar and aar dependency suffixes [#11161](https://github.com/mapbox/mapbox-gl-native/pull/11161) 

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.0.0-beta.2` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.0.0-beta.2` artifact to Maven Central
- [x] Tag `android-v6.0.0-beta.2` 
- [x] Change version name to `6.0.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.0.0-beta.2` back into `release-boba`
- [x] Update Javadoc documentation via release branch, _not_ `master` @langsmith 
- [x] Create new Fabric release @langsmith
- [ ] Update Mapbox demo and wearable demo apps @langsmith 
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] TBD: update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)
- [ ] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] If stable version, update version # in `android-docs` repo's `constants.js` file @langsmith 
- [ ] If stable version, update version # in `config` files in /help @langsmith
- [ ] If stable version, update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] If stable version, update version # in pthfndr @langsmith
- [ ] If stable version, update version # in Studio Preview @langsmith
- [ ] If stable version, update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [ ] If stable version, update version # in cnplgn @langsmith
- [ ] If stable version, update version # in cndocs @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by langsmith** [comment]
fyi @tobrun , unable to update demo app to beta.2 because location layer plugins haven't been updated to to 6.x yet

**Comment by langsmith** [comment]
@cammace , is there any update/ticket/pr related to the plugin getting 6.x of the maps sdk?

**Comment by tobrun** [comment]
@langsmith we should only publish plugin versions with final/stable versions of the SDK. For LocationLayer we are thinking about using the beta concept as well for releasing plugins with 6.0.0-beta.x.

Going to close this as we are releasing beta.3 today.
