### ISSUE TITLE
Release Android v5.5.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11348]
Today we release the 5.5.0 version of the Mapbox Maps SDK for Android.

### Changes since v5.4.0
  - TileJSON Bounds allows values inclusive of world extents [#11178](https://github.com/mapbox/mapbox-gl-native/pull/11178)
 - LatLngBounds returned by VisibleRegion when map is rotated [#11226](https://github.com/mapbox/mapbox-gl-native/pull/11226)
 - Custom Layer fixes & black list VAO on mali t720 [#11239](https://github.com/mapbox/mapbox-gl-native/pull/11239)
 - Check if Activity isn't finishing before showing dialog [#11244](https://github.com/mapbox/mapbox-gl-native/pull/11244)
 - Decouple MapPadding from overlain views [#11258](https://github.com/mapbox/mapbox-gl-native/pull/11258)
 - Don't disable zoom button controller zooming with gesture disabled zoom [#11259](https://github.com/mapbox/mapbox-gl-native/pull/11259)
 - Expose ImageSource coordinates setter [#11262](https://github.com/mapbox/mapbox-gl-native/pull/11262)
 - Add missing DeleteLocalRefs [#11272](https://github.com/mapbox/mapbox-gl-native/pull/11272)
 - Continue loading style even if we mutate it [#11294](https://github.com/mapbox/mapbox-gl-native/pull/11294)
 - Update telemetry version for OkHttp [#11338](https://github.com/mapbox/mapbox-gl-native/pull/11338)

 
### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.5.0` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.5.0` artifact to Maven Central
- [x] Tag `android-v5.5.0` 
- [x] Change version name to `5.5.1-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.5.0` back into `release-agua`
- [x] Update Javadoc documentation via release branch, _not_ `master` @langsmith 
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps @langsmith 
- [x] If stable version, update `mapbox-plugins-android` test app @langsmith
- [x] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in cndocs in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [x] Update version # in Studio Preview @langsmith
- [x] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [x] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [x] Release new version of Android demo app on Play Store @langsmith
- [x] ~~If not beta release, update version # in cnplgn @langsmith~~

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by langsmith** [comment]
🎉
