### ISSUE TITLE
Release Android v6.0.0-beta.3

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11368]
In preparation for release v6.0.0 of the Mapbox Android SDK, we're releasing today the third beta in the 6.0.x series. The 6.x release brings major features as:
 - Heatmap support
 - Refreshed gestures handling
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection
 - Transparent TextureView

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

Please note that this is a pre-release version intended to gather early feedback on the new APIs and to detect any potential issues (you can report them [here](https://github.com/mapbox/mapbox-gl-native/issues)). This release is not intended for production apps.

### Changes since v6.0.0-beta.2
 - Remove deprecated location APIs [#11351](https://github.com/mapbox/mapbox-gl-native/pull/11351)
 - Added missing local reference deletes [#11243](https://github.com/mapbox/mapbox-gl-native/pull/11243), [#11272](https://github.com/mapbox/mapbox-gl-native/pull/11272)
 - Remove obsolete camera api [#11201](https://github.com/mapbox/mapbox-gl-native/pull/11201)
 - Fix UTF-8 encoding, add missing package-info.java files [#11261](https://github.com/mapbox/mapbox-gl-native/pull/11261)
 - Rework expression api [#11210](https://github.com/mapbox/mapbox-gl-native/pull/11210)
 - LatLngBounds fixes [#11333](https://github.com/mapbox/mapbox-gl-native/pull/11333), [#11307](https://github.com/mapbox/mapbox-gl-native/pull/11307), [#11308](https://github.com/mapbox/mapbox-gl-native/pull/11308), [#11309](https://github.com/mapbox/mapbox-gl-native/pull/11309), [#11226](https://github.com/mapbox/mapbox-gl-native/pull/11226)
 - New gestures library [#11221](https://github.com/mapbox/mapbox-gl-native/pull/11221)
 - Expose ImageSource coordinates setter [#11262](https://github.com/mapbox/mapbox-gl-native/pull/11262)
 - Add heatmap color property [#11220](https://github.com/mapbox/mapbox-gl-native/pull/11220)
 - Add support for mapzen terrarium raster-dem encoding [#11339](https://github.com/mapbox/mapbox-gl-native/pull/11339)
### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.0.0-beta.3` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.0.0-beta.3` artifact to Maven Central
- [x] Tag `android-v6.0.0-beta.3` 
- [x] Change version name to `6.0.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.0.0-beta.3` back into `release-boba`
- [x] Update Javadoc documentation via release branch, _not_ `master` @langsmith 
- [x] Create new Fabric release @langsmith
- [ ] Update Mapbox demo and wearable demo apps @langsmith 
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] TBD: update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)
- [ ] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] If stable version, update version # in `android-docs` repo's `constants.js` file @langsmith 
- [ ] If stable version, update version # in `config` files in /help @langsmith
- [ ] If stable version, update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] If stable version, update version # in pthfndr @langsmith
- [ ] If stable version, update version # in Studio Preview @langsmith
- [ ] If stable version, update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [ ] If stable version, update version # in cnplgn @langsmith
- [ ] If stable version, update version # in cndocs @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by LukasPaczos** [comment]
Noting, that our upcoming `6.0.0` release includes support for Java 8 features, therefore in order to run it (or any of the betas) you need to upgrade your project to include Java 8 support by adding this into your app's gradle file:
```
android {
    ...
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
or enabling Java 8 support for your project from Android Studio menu.

**Comment by zugaldia** [comment]
> you need to upgrade your project to include Java 8 support by adding this into your app's gradle file

If this is a hard requirement, is this something that we could add to our Gradle config so that it applies automatically to consuming apps?

**Comment by tobrun** [comment]
>> you need to upgrade your project to include Java 8 support by adding this into your app's gradle file

> If this is a hard requirement, is this something that we could add to our Gradle config so that it applies automatically to consuming apps?

This is a hard requirement and imo we shouldn't require users to add this. I ticketed https://github.com/mapbox/mapbox-gl-native/issues/11392 to remove support from the SDK.

**Comment by langsmith** [comment]
Noting here that upgrading the demo app to any 6.x beta version is on hold because of the API breaking changes that come with 6.x. ; most notably, data-driven styling.

**Comment by LukasPaczos** [comment]
In order to test out this beta version in your app you need to add snapshot repository URL to your top level `build.gradle` file.
```
allprojects {
    repositories {
        google()
        mavenCentral()
        ...
        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```

This will not be required for the upcoming beta and stable releases, only `6.0.0-beta.3`.

**Comment by langsmith** [comment]
We good to close this @tobrun / @LukasPaczos ? Javadocs have been added to /android-docs and I created a new Fabric release. Demo app isn't being updated.

**Comment by LukasPaczos** [comment]
Good to close, thanks @langsmith.
