### ISSUE TITLE
Release Android v6.0.0-beta.4

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11484]
In preparation for release v6.0.0 of the Mapbox Android SDK, we're releasing today the fourth beta in the 6.0.x series. The 6.x release brings major features as:
 - Heatmap support
 - Refreshed gestures handling
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection
 - Transparent TextureView

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

Please note that this is a pre-release version intended to gather early feedback on the new APIs and to detect any potential issues (you can report them [here](https://github.com/mapbox/mapbox-gl-native/issues)). This release is not intended for production apps.

### Changes since v6.0.0-beta.3
 - TBA

### Todo 
- [ ] Create release branch
- [ ] Change CircleCI config to build from release branch (android-release-all->deploy)
- [ ] Change version name to `6.0.0-beta.4` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [ ] Publish `6.0.0-beta.4` artifact to Maven Central
- [ ] Tag `android-v6.0.0-beta.4` 
- [ ] Change version name to `6.0.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [ ] Change CircleCI config to build back from release branch
- [ ] Merge `release-android-v6.0.0-beta.4` back into `release-boba`
- [ ] Update Javadoc documentation via release branch, _not_ `master` @langsmith 
- [ ] Create new Fabric release @langsmith
- [ ] Update Mapbox demo and wearable demo apps @langsmith 
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] TBD: update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)
- [ ] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] If stable version, update version # in `android-docs` repo's `constants.js` file @langsmith 
- [ ] If stable version, update version # in `config` files in /help @langsmith
- [ ] If stable version, update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] If stable version, update version # in pthfndr @langsmith
- [ ] If stable version, update version # in Studio Preview @langsmith
- [ ] If stable version, update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [ ] If stable version, update version # in cnplgn @langsmith
- [ ] If stable version, update version # in cndocs @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by langsmith** [comment]
@tobrun , as discussed, we're not doing javadocs for beta releases anymore. Fabric release has been created for this beta release, so everything's done on my end for this.
