### ISSUE TITLE
Release Android v5.5.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11525]
Today we release the 5.5.1 version of the Mapbox Maps SDK for Android.

### Changes since v5.5.0
  - Verify optional access of FileSource deactivation [#11480](https://github.com/mapbox/mapbox-gl-native/pull/11480)
 - Prevent default style loading when style json was set [#11519](https://github.com/mapbox/mapbox-gl-native/pull/11519)
 - Delete local reference when convering Image.java [#11350](https://github.com/mapbox/mapbox-gl-native/pull/11350)
 - Use float for pixel ratio when creating a snapshotter [#11367](https://github.com/mapbox/mapbox-gl-native/pull/11367)
 - Validate if width and height aren't 0 when creating a snapshot [#11364](https://github.com/mapbox/mapbox-gl-native/pull/11364)
 - Null check body of http request [#11413](https://github.com/mapbox/mapbox-gl-native/pull/11413)
 - Clamp TileJSON bounds [#11425](https://github.com/mapbox/mapbox-gl-native/pull/11425)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.5.0` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.5.0` artifact to Maven Central
- [x] Tag `android-v5.5.0` 
- [x] Change version name to `5.5.1-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.5.0` back into `release-agua`
- [  ] If stable version, Make new cnplgn release @cammace
- [x] Update the `android-docs` repo's javadoc documentation via release branch, _not_ `master` @langsmith 
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps @langsmith 
- [x] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [ ] Update version # in Studio Preview @langsmith
- [x] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [x] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [x] Release new version of Android demo app on Play Store @langsmith
- [ ] ~~If not beta release, update version # in cnplgn @langsmith~~

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis
