### ISSUE TITLE
Release Android v6.0.0-beta.5

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11536]
In preparation for release v6.0.0 of the Mapbox Android SDK, we're releasing today the fifth beta in the 6.0.x series. The 6.x release brings major features as:
 - Heatmap support
 - Refreshed gestures handling
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection
 - Transparent TextureView

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

Please note that this is a pre-release version intended to gather early feedback on the new APIs and to detect any potential issues (you can report them [here](https://github.com/mapbox/mapbox-gl-native/issues)). This release is not intended for production apps.

### Changes since v6.0.0-beta.4
 - Avoid flashing on pitched overzoomed tiles [#11488](https://github.com/mapbox/mapbox-gl-native/pull/11488)
 - Literal array conversion of primitive arrays [#11500](https://github.com/mapbox/mapbox-gl-native/pull/11500)
 - Make default output from step more descriptive [#11501](https://github.com/mapbox/mapbox-gl-native/pull/11501)
 - Expose public Telemetry API [#11503](https://github.com/mapbox/mapbox-gl-native/pull/11503)
 - Convert Android int colors with to-color expression [#11506](https://github.com/mapbox/mapbox-gl-native/pull/11506)
 - Prevent default style reload when string style json was set [#11520](https://github.com/mapbox/mapbox-gl-native/pull/11520)
 - String, number and bool expressions with multiple values [#11512](https://github.com/mapbox/mapbox-gl-native/pull/11512)
 - Telemetry library 3.0.0-beta.3 [#11534](https://github.com/mapbox/mapbox-gl-native/pull/11534)
 - Gestures library v0.2.0 [#11535](https://github.com/mapbox/mapbox-gl-native/pull/11535)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.0.0-beta.5` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.0.0-beta.5` artifact to Maven Central
- [x] Tag `android-v6.0.0-beta.5` 
- [x] Change version name to `6.0.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.0.0-beta.5` back into `release-boba`
- [x] Update Javadoc documentation via release branch, _not_ `master` @langsmith
- [x] Create new Fabric release @langsmith
--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by langsmith** [comment]
Done on my end @LukasPaczos  🎆

**Comment by LukasPaczos** [comment]
🚀
