### ISSUE TITLE
Release Android v6.0.0-beta.6

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11591]
In preparation for release v6.0.0 of the Mapbox Android SDK, we're releasing today the sixth beta in the 6.0.x series. The 6.x release brings major features as:
 - Heatmap support
 - Refreshed gestures handling
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection
 - Transparent TextureView

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

Please note that this is a pre-release version intended to gather early feedback on the new APIs and to detect any potential issues (you can report them [here](https://github.com/mapbox/mapbox-gl-native/issues)). This release is not intended for production apps.

### Changes since v6.0.0-beta.5
 - Fix race condition crash for heavily modified annotations [#11551](https://github.com/mapbox/mapbox-gl-native/pull/11551)
 - Throw exception when converting PropertyValue with an expression [#11572](https://github.com/mapbox/mapbox-gl-native/pull/11572)
 - Invalidate camera position before delivering onMapReady [#11585](https://github.com/mapbox/mapbox-gl-native/pull/11585)
 - Rework logical condition convenience expressions [#11555](https://github.com/mapbox/mapbox-gl-native/pull/11555)
 - Telemetry library version bump to 3.0.0-beta.4 [#11590](https://github.com/mapbox/mapbox-gl-native/pull/11590)

### Todo 
- [ ] Create release branch
- [ ] Change CircleCI config to build from release branch (android-release-all->deploy)
- [ ] Change version name to `6.0.0-beta.6` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [ ] Publish `6.0.0-beta.6` artifact to Maven Central
- [ ] Tag `android-v6.0.0-beta.6` 
- [ ] Change version name to `6.0.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [ ] Change CircleCI config to build back from release branch
- [ ] Merge `release-android-v6.0.0-beta.6` back into `release-boba`
- [ ] Update Javadoc documentation via release branch, _not_ `master` @langsmith
- [ ] Create new Fabric release @langsmith
--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis
