### ISSUE TITLE
Release Android v5.5.2

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11645]
Today we release the 5.5.2 version of the Mapbox Maps SDK for Android.

### Changes since v5.5.1
 - Correct animation scale point [#11643](https://github.com/mapbox/mapbox-gl-native/pull/11643)
 - Re-bind uniform locations after re-linking program [#11583](https://github.com/mapbox/mapbox-gl-native/pull/11583)
 - Invalidate camera position before delivering onMapReady [#11585](https://github.com/mapbox/mapbox-gl-native/pull/11585)
 - Null java peer callback [#11358](https://github.com/mapbox/mapbox-gl-native/pull/11358)
 - Add missing delete local reference [#11608](https://github.com/mapbox/mapbox-gl-native/pull/11608)
 - Release local refs [#11599](https://github.com/mapbox/mapbox-gl-native/pull/11599)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.5.2` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.5.2` artifact to Maven Central
- [x] Tag `android-v5.5.2` 
- [x] Change version name to `5.6.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.5.2` back into `release-agua`
- [ ] If stable version, Make new cnplgn release @cammace
- [x] Update the `android-docs` repo's javadoc documentation via release tag's .zip folder @langsmith
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [ ] ~~Update Mapbox demo and wearable demo apps~~ @langsmith
- [ ] ~~If stable version, update `mapbox-plugins-android` test app~~ @langsmith
- [ ] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [x] Update version # in Studio Preview @langsmith
- [x] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [ ] ~~Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith~~
- [ ] ~~Release new version of Android demo app on Play Store @langsmith~~
- [ ] ~~If not beta release, update version # in cnplgn @langsmith~~

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by mb12** [comment]
@tobrun Can you have the following crash fixed for the release? Its consistently reproducible with the test application.

https://github.com/mapbox/mapbox-gl-native/issues/10414

**Comment by tobrun** [comment]
@mb12 not able to reproduce that crash. Which hardware were you testing on? Are you able to reproduce this consistently with any of the 6.0.0-beta releases?

**Comment by mb12** [comment]
@tobrun you will have to use a debug build since the mbgl_check_error macro is ifdef’ed out in Release build. I see that crash once every five minutes onSamsung Note 3 running 4.4.2.

**Comment by langsmith** [comment]
All done on my end
