### ISSUE TITLE
Release Android v6.0.0-beta.7

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11662]
In preparation for release v6.0.0 of the Mapbox Android SDK, we're releasing today the 7th beta in the 6.0.x series. The 6.x release brings major features as:
 - Heatmap support
 - Refreshed gestures handling
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection
 - Transparent TextureView

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

Please note that this is a pre-release version intended to gather early feedback on the new APIs and to detect any potential issues (you can report them [here](https://github.com/mapbox/mapbox-gl-native/issues)). This release is not intended for production apps.

### Changes since v6.0.0-beta.6
 - Add abs, round, floor, ceil expression operators [#11653](https://github.com/mapbox/mapbox-gl-native/pull/11653)
 - LatLngBounds correct center calculation [#11650](https://github.com/mapbox/mapbox-gl-native/pull/11650)
 - Bump telemetry to 3.0.0 final [#11658](https://github.com/mapbox/mapbox-gl-native/pull/11658)
 - Correctly calculate LatLngBounds [#11647](https://github.com/mapbox/mapbox-gl-native/pull/11647)
 - Add convenience step expression [#11641](https://github.com/mapbox/mapbox-gl-native/pull/11641)
 - Add javadoc examples for Android [#11540](https://github.com/mapbox/mapbox-gl-native/pull/11540)
 - Add paused state to map renderer, don't render snapshots after onPause [#11358](https://github.com/mapbox/mapbox-gl-native/pull/11358)
 - Rework internal expression conversion [#11490](https://github.com/mapbox/mapbox-gl-native/pull/11490)
 - Fixed gesture event listeners javadoc [#11630](https://github.com/mapbox/mapbox-gl-native/pull/11630)
 - Add delete local reference on jni strings [#11608](https://github.com/mapbox/mapbox-gl-native/pull/11608)
 - Release local references early [#11599](https://github.com/mapbox/mapbox-gl-native/pull/11599)
 - Re-bind uniform locations after re-linking program [#11618](https://github.com/mapbox/mapbox-gl-native/pull/11618)
 - Bump mapbox-sdk-services to 3.0.1 [#11593](https://github.com/mapbox/mapbox-gl-native/pull/11593)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.0.0-beta.7` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.0.0-beta.7` artifact to Maven Central
- [x] Tag `android-v6.0.0-beta.7` 
- [x] Change version name to `6.0.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.0.0-beta.7` back into `release-boba`
- [x] Update Javadoc documentation via release branch, _not_ `master` @langsmith
- [x] Create new Fabric release @langsmith
--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis
