### ISSUE TITLE
Release Android v6.0.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11702]
Today we are releasing the final version of Mapbox Maps SDK for Android v6.0.0.

### Key features
 - Heatmap support
 - Refreshed gestures handling
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection
 - Transparent TextureView

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

### Migration guide
Since this is a major version update, we are introducing a couple of API breaking changes and changing some of the project requirements. A full list of respective solutions can be found in the [migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-5.x-to-6.x-migration-guide).

### Feedback
Please report any issues you have with this release [here](https://github.com/mapbox/mapbox-gl-native/issues)). For support questions please use StackOverflow or reach out to us through [support](https://www.mapbox.com/contact/support/).

### Changes since v6.0.0-beta.7
 - Bump telemetry version to 3.0.1 [#11700](https://github.com/mapbox/mapbox-gl-native/pull/11700)
 - Update layer when changing its min/max zoom [#11687](https://github.com/mapbox/mapbox-gl-native/pull/11687)

The full log with all changes introduced since 5.0 can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CHANGELOG.md).

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.0.0` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.0.0` artifact to Maven Central
- [x] Tag `android-v6.0.0` 
- [x] Change version name to `6.0.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.0.0` back into `release-agua`
- [ ] If stable version, Make new cnplgn release @cammace
- [ ] Update the `android-docs` repo's javadoc documentation via release tag's .zip folder @langsmith
- [ ] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [ ] Update Mapbox demo and wearable demo apps @langsmith
- [ ] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [ ] Update version # in `config` files in /help @langsmith
- [ ] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] Update version # in pthfndr @langsmith
- [ ] Update version # in Studio Preview @langsmith
- [ ] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [ ] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] If not beta release, update version # in cnplgn @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by LukasPaczos** [comment]
Re. https://github.com/mapbox/mapbox-gl-native/issues/11708#issuecomment-381984749.
If you are seeing `Could not find com.mapbox.mapboxsdk:mapbox-android-core:0.3.0-SNAPSHOT` error, please include below lines in your top level `build.gradle` file:
```
allprojects {
    repositories {
        jcenter()
        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
        ...
    }
}
```
