### ISSUE TITLE
Release Android v6.0.1

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11712]
Today we are releasing the 6.0.1 version of Mapbox Maps SDK for Android.

### Key features
 - Heatmap support
 - Refreshed gestures handling
 - Expressions
 - HillshadeLayer and RasterDemSource
 - CustomGeometrySource
 - ViewportCollision detection
 - Transparent TextureView

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

### Migration guide
Since this is a major version update, we are introducing a couple of API breaking changes and changing some of the project requirements. A full list of respective solutions can be found in the [migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-5.x-to-6.x-migration-guide).

### Feedback
Please report any issues you have with this release [here](https://github.com/mapbox/mapbox-gl-native/issues). For support questions please use StackOverflow or reach out to us through [support](https://www.mapbox.com/contact/support/).

### Changes since v6.0.0
 - Bump telemetry version to 3.0.2 [#11710](https://github.com/mapbox/mapbox-gl-native/pull/11710)

The full log with all changes introduced since 5.0 can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CHANGELOG.md).

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.0.1` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.0.1` artifact to Maven Central
- [x] Tag `android-v6.0.1` 
- [x] Change version name to `6.1.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.0.1` back into `release-boba`
- [x] If stable version, Make new cnplgn release @cammace
- [x] Update the `android-docs` repo's javadoc documentation via release tag's .zip folder @langsmith
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps @langsmith
- [x] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [x] Update version # in Studio Preview @langsmith
- [x] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [x] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] If stable version, update # in cnplgn @langsmith
- [ ] If stable version, update # in vyge @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis
