### ISSUE TITLE
Many NSPredicate and NSExpression operators have no equivalent in style JSON

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11786]
This issue tracks progress toward supporting the full range of NSPredicate and NSExpression functions and operators, based on where we are in iOS map SDK v4.0.0 and macOS map SDK v0.7.0. mapbox/mapbox-gl-js#6484 is a corresponding issue that tracks several style specification additions that would block this goal.

Some of these operators already have workarounds. It isn’t necessary to support _all_ of these operators, since some may be a poor fit for manipulating a style. Developers are used to – if sometimes frustrated by – the fact that various Core Data and NSArray backends support different subsets of the NSPredicate and NSExpression vocabulary and grammar.

* [ ] Types
  * [ ] NSSet
  * [ ] NSDate
  * [ ] CLLocation
* [ ] [Basic comparisons](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html#//apple_ref/doc/uid/TP40001795-215832)
  * [ ] `BETWEEN` (worked around in v4.0.0/v0.7.0)
* [ ] [String comparisons](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html#//apple_ref/doc/uid/TP40001795-215868)
  * [ ] `BEGINSWITH`
  * [ ] `CONTAINS` (currently only supported for array membership): mapbox/mapbox-gl-js#4113
  * [ ] `ENDSWITH`
  * [ ] `LIKE`
  * [ ] `MATCHES`: mapbox/mapbox-gl-js#6228
  * [ ] `UTI-CONFORMS-TO` (probably not needed)
  * [ ] `UTI-EQUALS` (probably not needed)
* [ ] Aggregate expressions: mapbox/mapbox-gl-js#6155
* [ ] [Aggregate operations](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html#//apple_ref/doc/uid/TP40001795-215891)
  * [ ] `ANY`, `SOME`
  * [ ] `ALL`
  * [ ] `NONE`
  * [ ] `IN` (`MATCH` is sort of a workaround): mapbox/mapbox-gl-js#4698 mapbox/mapbox-gl-js#6950 #12415
  * [x] `array[FIRST]`: #11770
  * [x] `array[LAST]`: #11770
  * [x] `array[SIZE]`: #11770
* [ ] `SUBQUERY` (like a [list comprehension](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Generator_comprehensions))
* [ ] Set operations
  * [ ] `UNION` (not supported by Core Data)
  * [ ] `INTERSECT` (not supported by Core Data)
  * [ ] `MINUS` (not supported by Core Data)
* [ ] Operator modifiers
  * [x] `c` for case insensitivity: #11692 #12329
  * [x] `d` for diacritic insensitivity: mapbox/mapbox-gl-js#4136 #12329
  * [ ] `l` for locale insensitivity: #11692 #12269
  * [ ] `n` for normalization
* [ ] [Functions](https://developer.apple.com/documentation/foundation/nsexpression/1413747-init#discussion)
  * [ ] `average:` (worked around in v4.0.0/v0.7.0)
  * [ ] `median:`: mapbox/mapbox-gl-js#5853
  * [ ] `mode:`: mapbox/mapbox-gl-js#5853
  * [ ] `stddev:`: mapbox/mapbox-gl-js#5853
  * [ ] `exp:` (worked around in v4.0.0/v0.7.0): mapbox/mapbox-gl-js#5853
  * [ ] `trunc:` (worked around in v4.0.0/v0.7.0)
  * [ ] `random`: mapbox/mapbox-gl-js#5853
  * [ ] `randomn:`: mapbox/mapbox-gl-js#5853
  * [ ] `now`
  * [ ] `bitwiseAnd:with:`
  * [ ] `bitwiseOr:with:`
  * [ ] `bitwiseXor:with:`
  * [ ] `leftshift:by:`
  * [ ] `rightshift:by:`
  * [ ] `onesComplement:`
  * [ ] `distanceToLocation:fromLocation:`: mapbox/mapbox-gl-js#6062
* [ ] [Collection operators](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/KeyValueCoding/CollectionOperators.html)
  * [ ] `array.subkey` (mapping an array to a subkey of its elements)
  * [ ] `@avg`
  * [ ] `@count`
  * [ ] `@min`
  * [ ] `@max`
  * [ ] `@sum`
  * [ ] `@distinctUnionOfObjects`
  * [ ] `@unionOfObjects`
  * [ ] `@distinctUnionOfArrays`
  * [ ] `@unionOfArrays`
  * [ ] `@distinctUnionOfSets`
* [ ] Casts – technically, any Objective-C object can be cast to an NSString, but the items below are for expected use cases
  * [ ] NSArray → NSString
  * [ ] NSDictionary → NSString
  * [ ] NSDate → NSString
  * [ ] NSColor/UIColor → NSString
  * [ ] NSArray → NSString
  * [ ] NSString → NSDate
  * [ ] NSNumber → NSDate
* [ ] Block expressions – blocked by #7860

(Sources for this issue included Realm’s “[NSPredicate Cheatsheet](https://academy.realm.io/posts/nspredicate-cheatsheet/)”.)

/ref mapbox/mapbox-gl-js#5892
/cc @fabian-guerra @anandthakker @ChrisLoer

**Comment by 1ec5** [comment]
I added a note that block expressions are, ahem, blocked by core support as described in #7860. If there’s any way at all that we could support arbitrary executable code as part of style property evaluation, we should definitely consider it, because developers find it _much_ more straightforward to use ordinary programming language affordances than to learn a declarative mini-language, be it NSExpression format strings or anything we’d implement in the style spec for Turing completeness.
