### ISSUE TITLE
Release Android v5.5.3

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11836]
Today we release the 5.5.3 version of the Mapbox Maps SDK for Android.

### Changes since v5.5.2
 - Check if renderer is not destroyed before delivering snapshot [#11800](https://github.com/mapbox/mapbox-gl-native/pull/11800)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.5.3` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.5.3` artifact to Maven Central
- [x] Tag `android-v5.5.3` 
- [x] Change version name to `5.6.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.5.3` back into `release-agua`
- [x] If stable version, Make new cnplgn release @cammace
- [x] Update the `android-docs` repo's javadoc documentation via release tag's .zip folder @langsmith
- [ ] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [ ] ~~Update Mapbox demo and wearable demo apps~~ @langsmith
- [ ] ~~If stable version, update `mapbox-plugins-android` test app~~ @langsmith
- [ ] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [ ] Update version # in `config` files in /help @langsmith
- [ ] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] Update version # in pthfndr @langsmith
- [ ] Update version # in Studio Preview @langsmith
- [ ] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [ ] Create new Fabric release @langsmith
- [ ] ~~Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith~~
- [ ] ~~Release new version of Android demo app on Play Store @langsmith~~
- [ ] ~~If not beta release, update version # in cnplgn @langsmith~~

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by langsmith** [comment]
@tobrun  I added javadocs to `/android-docs` for this release. I don't think anything else needs to be done for `5.5.3` because [there's 6.1.0](https://github.com/mapbox/mapbox-gl-native/issues/11834)
