### ISSUE TITLE
Release Android v6.1.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11834]
Today we are releasing the 6.1.0 version of Mapbox Maps SDK for Android.

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

### Feedback
Please report any issues you have with this release [here](https://github.com/mapbox/mapbox-gl-native/issues). For support questions please use StackOverflow or reach out to us through [support](https://www.mapbox.com/contact/support/).

### Changes since v6.0.1
 - Unwrap LatLngBounds during JNI conversion [#11807](https://github.com/mapbox/mapbox-gl-native/pull/11807)
 - Check if renderer is not destroyed before delivering snapshot [#11800](https://github.com/mapbox/mapbox-gl-native/pull/11800)
 - Null-check source before removing [#11789](https://github.com/mapbox/mapbox-gl-native/pull/11789)
 - Flutter support: promote pixel-ratio to public API NativeMapView [#11772](https://github.com/mapbox/mapbox-gl-native/pull/11772)
 - Unwrap LatLngBounds for the shortest path when requesting camera [#11759](https://github.com/mapbox/mapbox-gl-native/pull/11759)
 - Flutter support: integrate view callback abstraction [#11706](https://github.com/mapbox/mapbox-gl-native/pull/11706)
 - Match expression doc tweaks [#11691](https://github.com/mapbox/mapbox-gl-native/pull/11691)
 - Improve stop javadoc to include interpolate [#11677](https://github.com/mapbox/mapbox-gl-native/pull/11677)
 - Reduce per-frame render CPU time [#11811](https://github.com/mapbox/mapbox-gl-native/issues/11811)
 - Add Korean localization [#11792](https://github.com/mapbox/mapbox-gl-native/pull/11792)
 - Add Danish localization; update Hungarian, Russian, Swedish translations [#11136](https://github.com/mapbox/mapbox-gl-native/pull/11136)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.1.0` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.1.0` artifact to Maven Central
- [x] Tag `android-v6.1.0` 
- [x] Change version name to `6.1.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.0.1` back into `release-boba`
- [x] If stable version, Make new cnplgn release @cammace
- [x] Update the `android-docs` repo's javadoc documentation via release tag's .zip folder @langsmith
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [ ] Update Mapbox demo and wearable demo apps @langsmith
- [x] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [ ] Update version # in pthfndr @langsmith
- [ ] Update version # in Studio Preview @langsmith
- [ ] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [ ] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [ ] Release new version of Android demo app on Play Store @langsmith
- [ ] If stable version, update # in cnplgn @langsmith
- [ ] If stable version, update # in vyge @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis
