### ISSUE TITLE
Release Android v6.1.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11857]
Today we are releasing the 6.1.1 version of Mapbox Maps SDK for Android.

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

### Feedback
Please report any issues you have with this release [here](https://github.com/mapbox/mapbox-gl-native/issues). For support questions please use StackOverflow or reach out to us through [support](https://www.mapbox.com/contact/support/).

### Changes since v6.1.0
  - Update telemetry to 3.1.0 [#11855](https://github.com/mapbox/mapbox-gl-native/pull/11855)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.1.1` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.1.1` artifact to Maven Central
- [x] Tag `android-v6.1.1` 
- [x] Change version name to `6.2.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.1.1` back into `release-boba`
- [x] If stable version, Make new cnplgn release @cammace
- [x] Update the `android-docs` repo's javadoc documentation via release tag's .zip folder @langsmith
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps @langsmith
- [x] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [x] Update version # in Studio Preview @langsmith
- [x] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [x] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [x] Release new version of Android demo app on Play Store @langsmith
- [x] If stable version, update # in cnplgn @langsmith
- [ ] If stable version, update # in vyge @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by langsmith** [comment]
Unless I need to `update the style specification’s SDK support tables`, I believe everything's done on my end here. My understanding is that @danesfeder & @Guardiola31337 are in the process of updating `vyge`.
