### ISSUE TITLE
Release Android v6.1.3

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11990]
Today we are releasing the 6.1.3 version of Mapbox Maps SDK for Android.

![device-2018-02-28-190723](https://user-images.githubusercontent.com/16925074/36890745-58224f16-1dff-11e8-8483-0468743168eb.png)

### Feedback
Please report any issues you have with this release [here](https://github.com/mapbox/mapbox-gl-native/issues). For support questions please use StackOverflow or reach out to us through [support](https://www.mapbox.com/contact/support/).

### Changes since v6.1.2
 - Circle querying fixes [#11571](https://github.com/mapbox/mapbox-gl-native/pull/11571)
 - Global symbol query [#11742](https://github.com/mapbox/mapbox-gl-native/pull/11742)
 - Change MapView#initialize modifier to allow overriding [#11969](https://github.com/mapbox/mapbox-gl-native/pull/11969)
 - Update telemetry to 3.1.2 [#11987](https://github.com/mapbox/mapbox-gl-native/pull/11987)

### Todo 
- [x] Create release branch
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `6.1.3` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `6.1.3` artifact to Maven Central
- [x] Tag `android-v6.1.3` 
- [x] Change version name to `6.1.4-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v6.1.3` back into `release-boba`
- [x] If stable version, Make new cnplgn release @cammace
- [x] Update the `android-docs` repo's javadoc documentation via release tag's .zip folder @langsmith
- [x] Update SDK version in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps @langsmith
- [x] If stable version, update `mapbox-plugins-android` test app @langsmith
- [ ] update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Update version # in pthfndr @langsmith
- [x] Update version # in Studio Preview @langsmith
- [x] Update version # in `master`&`navUI` branches of [Store Locator kit](https://github.com/mapbox/store-locator-android) @langsmith
- [x] Create new Fabric release @langsmith
- [x] Create new tag/release in [demo app repo](https://github.com/mapbox/mapbox-android-demo) @langsmith
- [x] Release new version of Android demo app on Play Store @langsmith
- [x] If stable version, update # in cnplgn @langsmith
- [x] If stable version, update # in vyge @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support  @colleenmcginnis

**Comment by yeyeya1008** [comment]
Hello,
I was using v6.1.1 for my app.
Today, I changed sdk version up as v6.1.3.
There is a problem with clustering after that.
If some marker is unclustered, it has to be shown only it's own icon.
But I can only see clustering icon not unclustered icon.
What can i do to fix this?

**Comment by ben-j69** [comment]
The SDK v6 does not work because of telemtry issue

`java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.mapbox.android.telemetry.TelemetryService$TelemetryBinder
        at com.mapbox.android.telemetry.MapboxTelemetry$3.onServiceConnected(MapboxTelemetry.java:374)`

**Comment by langsmith** [comment]
@tobrun @LukasPaczos , this is done on my end...

**Comment by stoefln** [comment]
@ben-j69 same here

**Comment by stoefln** [comment]
I am referring to 

> java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.mapbox.android.telemetry.TelemetryService

**Comment by zugaldia** [comment]
@ben-j69 @stoefln Please see https://github.com/mapbox/mapbox-gl-native/issues/11994#issuecomment-391988090 - this crash should be fixed now. If not, please do [let us know](https://github.com/mapbox/mapbox-gl-native/issues/new). Thanks!

**Comment by BharathMG** [comment]
@zugaldia We are seeing `android.os.BinderProxy cannot be cast to com.mapbox.android.telemetry.TelemetryService$TelemetryBinder` sometimes in 6.2.1 on application stop events.

**Comment by zugaldia** [comment]
> @zugaldia We are seeing android.os.BinderProxy cannot be cast to com.mapbox.android.telemetry.TelemetryService$TelemetryBinder sometimes in 6.2.1 when app starts or stops.

@electrostat Is https://github.com/mapbox/mapbox-events-android/issues/174 the best place to track this issue, or should we cut a new one?

**Comment by electrostat** [comment]
@zugaldia yep that's the best place to track it. On my list to get to and start investigating/solving.

@BharathMG could you provide some example code for me to test my solution against?

**Comment by rhuttenh** [comment]
I am on version 6.2.1 of the sdk and version 0.2.0 of core with the current plugins. I am still getting this error in my service that issue location updates to the UI. I was able to fix the issue for now by including 
<meta-data android:name="com.mapbox.EnableEvents" android:value="false" /> in my manifest.
Do you have a fix for this yet?

**Comment by electrostat** [comment]
@rhuttenh @BharathMG check the latest snapshot of core: `0.3.0-SNAPSHOT`. It should have the fix you need. If you are still running into issues, please reach out in our events repo: https://github.com/mapbox/mapbox-events-android

**Comment by rhuttenh** [comment]
Nope that did not work. Still the same error. I turned it back on in my manifest so that I can continue work.
What are my next steps to help you fix the error. I am new to filing issues on GitHub.  Sorry

**Comment by electrostat** [comment]
@rhuttenh use this link: https://github.com/mapbox/mapbox-events-android/issues/new and provide all the details of the bug you are experiencing. Crash logs would be helpful. Additionally, please provide a code example so I can replicate the bug. Any other details that you think would be helpful would be appreciated (OS version, devices crash is occurring on, sdk versions, etc...)
