### ISSUE TITLE
Convert iOS Telemetry To V2 Data Model

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#4148]
This was started in https://github.com/mapbox/mapbox-gl-native/pull/3620. We should update the event model serialization to be compatible with the V2 spec and post the the V2 endpoint.

##### Tasks

- [x] Update turnstile event
- [x] Update map load event
- [x] Update map click event
- [x] Update map drag end event
- [x] Update location event
- [x] Stop sending visits (already done in master)
- [x] Reduce lat/lng precision to 7 digits
- [x] Update the user agent to include the SDK version
- [x] Pull in anything from https://github.com/mapbox/mapbox-gl-native/pull/3620/commits that still makes sense
- [x] Use location manager timestamp on location events instead of artificial one
- [x] Decide if we want core telephony for `carrier` and `cellularNetworkType` (see https://github.com/mapbox/mapbox-gl-native/issues/3295)
- [x] Change session id based on time boundary like [MapboxEventManager.java](https://github.com/mapbox/mapbox-gl-native/blob/5ac6fc523dea6374da7ba15a7c0433b115987ed2/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java#L375-L381)
- [x] Add hook to catch network requests that receive a troublesome status code
- [x] Make the flush timeouts slightly less aggressive (20 events or 60 seconds -> 180 events or 180 seconds)

cc @camilleanne @mick

**Comment by boundsj** [comment]
We've decided to punt on bringing back Core Telephony for now. `carrier` and `cellularNetworkType` will not be sent in v3.2.0
