### ISSUE TITLE
UserLocationView refactor

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4396]
As mentioned IRL, we need to rewrite `UserLocationView` from scratch. The list below shows the issues we have with current implementation, some of these can only be resolved by starting from scratch:

- [x] Start from scratch
- [x] Implement onMeasure / onDraw with a foreground drawable and shadow drawable
- [x] Add Arrow / acuracy circle
- [x] Integrate into existing project/requirements
- [x] Make a distinction between tracking and non tracking behaviour
- [x] Missing tilt support https://github.com/mapbox/mapbox-gl-native/issues/3189
- [x] Padding https://github.com/mapbox/mapbox-gl-native/issues/3947
- [x] Performance of accuracy circle https://github.com/mapbox/mapbox-gl-native/issues/3078
- [x] Configurability of used resources https://github.com/mapbox/mapbox-gl-native/pull/4137
- [x] Possibility of tinting https://github.com/mapbox/mapbox-gl-native/issues/3231
- [x] Smooth animation when location changes https://github.com/mapbox/mapbox-gl-native/issues/3629
- [x] ~~Possibility of replacing the UserLocationView with an user provided implementation*~~

@zugaldia 
The * item should help support the idea of introducing a separate navigation mode. Not sure how this will translate to our current exposed tracking modes as `MyBearingTracking` and `MyLocationTracking`. But I'm currently thinking we can extract logic through interfaces (eg. keeping the view insync with the location of the user) and the dependencies it has with gestures could be replaced with a more general configuration as requested in #4151. To make that all possible we will need multiple abstractions.

cc @bleege

**Comment by tobrun** [comment]
Step one here is to start from scratch and try getting in the same details as before. 
The biggest chance that also will help with #3189 and #3947, is making the UserLocationView do `WRAP_CONTENT` instead of `MATCH_PARENT`

**Comment by tobrun** [comment]
The previous implementation had a lot if - else checks based on type of tracking. For this refactor I'm thinking about doing 2 separate views or introducing a behaviour model within the view.

**Comment by tobrun** [comment]
Another item I'm looking at is using LayerDrawables to layer different drawables on top of each other and see if the subclass TransitionDrawable can help with this.

**Comment by tobrun** [comment]
First task is a success, I was able to create a custom view with 2 drawables aligned on top of eachother using WRAP_CONTENT. This is the first step to :rocket:. I'm now optimising that the foreground drawable is bigger than the background and visa versa. This is needed to correctly calculate the correct bounds of the drawables.

**Comment by tobrun** [comment]
I'm able to show a background image that is larger and I'm able to show a background image with same size and with an offset this all works correctly for left-top, now need to look into right-bottom configurations.

**Comment by tobrun** [comment]
Today I was able to correctly calculate bounds and having offsets to the drawables.

**Comment by bleege** [comment]
> Today I was able to correctly calculate bounds and having offsets to the drawables.

:boom:

**Comment by tobrun** [comment]
I implemented support for tilting, result of this can be seen in the child ticket. https://github.com/mapbox/mapbox-gl-native/issues/3189#issuecomment-207240034

**Comment by tobrun** [comment]
I implemented support for tinting, result of this can be seen in the child ticket. https://github.com/mapbox/mapbox-gl-native/issues/3231#issuecomment-207250070

**Comment by tobrun** [comment]
I have been working in a separate project, to get those changes in this project I'm starting from a #4626 and will gradually add/replace code from it.

**Comment by tobrun** [comment]
Just noticing some side cases are not correct when calculating bounds. The only good way to do this is supporting my changes with unit tests.

**Comment by tobrun** [comment]
Both tests and UI ar looking good, we can start with integration:

![screen shot 2016-04-12 at 11 41 47](https://cloud.githubusercontent.com/assets/2151639/14456125/a7d00ed4-00a3-11e6-98f1-2017ad2a69e6.png)
![screen shot 2016-04-12 at 11 41 55](https://cloud.githubusercontent.com/assets/2151639/14456126/a7d2488e-00a3-11e6-89fa-17a0a5beafcb.png)

**Comment by tobrun** [comment]
Added direction:
The star indicates direction and all UserLocationViews in the left column are set to 220 degrees.

![screen shot 2016-04-12 at 12 14 22](https://cloud.githubusercontent.com/assets/2151639/14457036/4fee6b48-00a8-11e6-9e43-c31c60294558.png)

**Comment by tobrun** [comment]
Added accuracy circle:

![screen shot 2016-04-12 at 14 44 32](https://cloud.githubusercontent.com/assets/2151639/14460296/15d39edc-00bd-11e6-9e12-734eb1f6cb58.png)

**Comment by tobrun** [comment]
Different accuracy levels: 100/80/60/40/20

![screen shot 2016-04-12 at 15 20 45](https://cloud.githubusercontent.com/assets/2151639/14461305/36e13f58-00c2-11e6-8a5c-91ba445d74d0.png)

**Comment by tobrun** [comment]
Now also possible to tint the accuracy circle and change alpha:
![screen shot 2016-04-12 at 15 28 14](https://cloud.githubusercontent.com/assets/2151639/14461504/317bf020-00c3-11e6-96e0-43f6125e9971.png)

**Comment by mb12** [comment]
@tobrun the white halo circle looks clipped on the right and left. Maybe the image/View canvas need to have size slightly more than circle diameter.

**Comment by tobrun** [comment]
@mb12 
that clipping is found in the images itself.. 
After porting this to the SDK with other images. this shouldn't happen anymore.
Thanks for the 👀  though!

**Comment by tobrun** [comment]
First steps of bringing this back to the SDK:
![screen shot 2016-04-13 at 08 54 57](https://cloud.githubusercontent.com/assets/2151639/14485140/6d3a7c20-0155-11e6-8bbc-109dd78a218b.png)

**Comment by tobrun** [comment]
This shows there is some bug in calculating bounds and as a result the UserLocationView is not correctly placed on the map. 

![screen shot 2016-04-13 at 09 03 11](https://cloud.githubusercontent.com/assets/2151639/14485310/91b4b358-0156-11e6-9f46-799ce05b7b37.png)

**Comment by tobrun** [comment]
Bounds issue figured out, next step is integration the previous features:

![screen shot 2016-04-13 at 09 24 16](https://cloud.githubusercontent.com/assets/2151639/14485787/86eb706c-0159-11e6-8ed8-c6962eb919d2.png)

**Comment by tobrun** [comment]
I had to rework the current images a bit but the result is the ability to tint:

![screen shot 2016-04-13 at 10 35 32](https://cloud.githubusercontent.com/assets/2151639/14487555/7b173744-0163-11e6-88ac-e37f80ef0b40.png)


I will have to ping @tatsvc to help me create the correct images.

**Comment by tobrun** [comment]
This is how tilt will be visually shown on the map:

![device-2016-04-13-105051](https://cloud.githubusercontent.com/assets/2151639/14487923/b3cc91ea-0165-11e6-9552-ea465955c171.png)

**Comment by tobrun** [comment]
MyLocationTracking enabled is working as before (disabling panning gesture and making the centre of the gesture equal to the centre of UserLocationView)

**Comment by tobrun** [comment]
While getting some features working again, I'm also noticing there is a fair amount of code rot. I think for future proofing the UserLocationView it's better to remove this rot altogether and also start partially from scratch.

**Comment by bleege** [comment]
This is looking great @tobrun!  I love seeing the screenshots as things progress.  Very cool!

>  I'm also noticing there is a fair amount of code rot. I think for future proofing the UserLocationView it's better to remove this rot altogether and also start partially from scratch.

Totally the right call IMHO.  :+1:

**Comment by tobrun** [comment]
This cleanup I'm thinking about will result in implementing:
>  Make a distinction between tracking and non tracking behaviour

This should allow building behaviours based on configured tracking modes  (Factory pattern)
and will remove a whole lot of `if else` tracking mode checks.

**Comment by tobrun** [comment]
We used to have multiple places in code with this kind of construction:

```java
        if (myLocationTrackingMode == MyLocationTracking.TRACKING_NONE && myBearingTrackingMode == MyBearingTracking.GPS) {
            //blabla
        } else if (myLocationTrackingMode == MyLocationTracking.TRACKING_FOLLOW && myBearingTrackingMode == MyBearingTracking.GPS) {
            //blabla
        }
```


This has now been replaced with a Factory that return a behaviour model on how the UserLocationView must behave in a certain configuration. This is now mostly refactored for usage of UserLocationTracking, it's not yet refactored for bearing.

```java
 private class UserLocationBehaviourFactory {

        public UserLocationBehaviour getBehaviouralModel(@MyLocationTracking.Mode int mode) {
            if (mode == MyLocationTracking.TRACKING_NONE) {
                return new UserLocationShowBehaviour();
            } else {
                return new UserLocationTrackingBehaviour();
            }
        }
    }

    private abstract class UserLocationBehaviour {
        
        abstract void update(Location location);

        public void update(double lat, double lon) {
            latLng.setLatitude(lat);
            latLng.setLongitude(lon);
        }

        abstract void invalidate();

        abstract void onDraw(UserLocationView userLocationView);

        public PointF getScreenLocation() {
            invalidate();
            return screenLocation;
        }
    }

    private class UserLocationTrackingBehaviour extends UserLocationBehaviour {

        @Override
        void update(Location location) {
            if (latLng == null || !latLng.equals(new LatLng(location))) {
                latLng = new LatLng(location);
                CameraPosition cameraPosition = new CameraPosition.Builder()
                        .target(latLng)
                        .build();
                mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition), 300, null);
            }
        }

        @Override
        void invalidate() {
            int[] contentPadding = mapboxMap.getPadding();
            UiSettings uiSettings = mapboxMap.getUiSettings();
            screenLocation = new PointF(((uiSettings.getWidth() - getWidth() + contentPadding[0] - contentPadding[2]) / 2)
                    , ((uiSettings.getHeight() - getHeight() - contentPadding[3] + contentPadding[1]) / 2));
        }

        @Override
        void onDraw(UserLocationView userLocationView) {
            setX(screenLocation.x);
            setY(screenLocation.y);
        }
    }

    private class UserLocationShowBehaviour extends UserLocationBehaviour {

        @Override
        void update(Location location) {
            LatLng previousCoordinate;
            if (latLng == null) {
                previousCoordinate = new LatLng(location);
            } else {
                previousCoordinate = latLng;
            }

            latLng = new LatLng(location);
            mMarkerCoordinateAnimator = ValueAnimator.ofFloat(0.0f, 1.0f);
            mMarkerCoordinateAnimator.setDuration(1000);
            mMarkerCoordinateAnimator.addUpdateListener(new MarkerCoordinateAnimatorListener(this, previousCoordinate, latLng));
            mMarkerCoordinateAnimator.start();
        }

        @Override
        void invalidate() {
            screenLocation = projection.toScreenLocation(latLng);
        }

        @Override
        void onDraw(UserLocationView userLocationView) {
            if (screenLocation != null) {
                setX(screenLocation.x - getWidth() / 2);
                setY(screenLocation.y - getHeight() / 2);
            }
        }
```

**Comment by tobrun** [comment]
I got almost everything from `4.0.0` back working, just have some side effect bugs while switching through the different modes and I still need to validate the compass bearing integration (my compass sensor is not working on my test device)

**Comment by tobrun** [comment]
Compass bearing integration has landed, it's not animating in the same way it did before. Going to punt on this for now. Next up is integrating accuracy/stale (I totally forgot that we had those features)

**Comment by tobrun** [comment]
Supporting changes above, I'm thinking about creating a separate feature activity for showcasing customisation options.

**Comment by tobrun** [comment]
@bleege @zugaldia @cammace 
I'm thinking about renaming `UserLocationView` to `MyLocationView`. Note that I'm not a big fan of the whole `MyLocationX` naming but we decided to keep this for parity with Google. I'm now noticing that we still use 2 names to describe the same thing (`UserLocation` and `MyLocationView`). Since the reason for keeping `MyLocation` seems more significant. I'm going to rename  `UserLocationView` to `MyLocationView`.

**Comment by tobrun** [comment]
Today continuing with map padding and adding padding to UserLocationView itself

**Comment by tobrun** [comment]
Last item on the list before bug fixes is smooth user location tracking using entity interpolation.

**Comment by tobrun** [comment]
Adding a note here that iOS performs a flyTo animation at initial startup of user tracking mode:

> When user tracking is initially enabled, MGLMapView “flies” to the first location reported by Core Location. This process may take longer than a second, but it gives the user more context as to their current location than the standard easing that MapKit performs.

**Comment by tobrun** [comment]
While implementing the entity interpolation logic,I'm noticing it's smoother but I'm still noticing a start/end position. This is probably due current setup that is constantly creating a new animation object. We should see if we can create it once and update it appropriately. The methods `setCurrentPlayTime` and `setCurrentFraction` will allow me to hook into an already running and sync time between the different updates and ongoing animations.

**Comment by tobrun** [comment]
I'm still having trouble integrating the interpolation logic for when tracking mode is not enabled. On the positive side I was able to implement interpolation logic for when tracking is enabled. See result [here](https://www.dropbox.com/s/u5mis46vq54kkvs/device-2016-04-19-150822.mp4?dl=0).

**Comment by tobrun** [comment]
The final missing feature is smooth animation tracking while we are not tracking the user. An example how tracking works versus not tracking isn't can be seen [here](https://www.dropbox.com/s/l8qnl7f4tbjespk/device-2016-04-20-114659.mp4?dl=0). The problem we have for Android which isn't an issue for iOS is that we use an ValueAnimator to animate the UserLocaitonView. This ValueAnimator uses time to calculate the required interpolation which automatically indicates such an animation has a start and an ending. Which conflicts with our use-case since we constantly want to animate the location changes.

**Comment by tobrun** [comment]
Without writing an own animation I don't think it's possible to completely get the UX we want. For now I was able to optimise the timing and the used interpolator to get a good as possible result. You can see the changes this in action [here](https://www.dropbox.com/s/r2cjxmv2tarf97d/device-2016-04-20-124139.mp4?dl=0). I'm going to cleanup the code, fix some small bugs and finish up the PR.

**Comment by tobrun** [comment]
It seems that gesture dismissing is broken, need to fix this before merging

**Comment by tobrun** [comment]
We don't have stale implemented now, when we bring it back it should be make optional/configurable.

**Comment by tobrun** [comment]
Adding note here that it sometimes takes a while before the style of the userdot is updated from the default one. Need to move initialisation. This will require exposing it as an attribute or exposing a method on MapView directly instead of configuration on MapboxMap.

**Comment by tobrun** [comment]
Noticing the same bug as iOS used to have with the location dot going backwards before going forwards

**Comment by tobrun** [comment]
Going to PR current progress and create tickets for the remaining items

**Comment by zugaldia** [comment]
@tobrun so excited to try the new behavior!
