### ISSUE TITLE
Release Android 4.2.0 Beta

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5871]
Mapbox Android 4.2.0 will bring a couple of major improvements to the Android SDK. This includes new features, improved performance and overall bugfixes. To help us produce a high quality stable SDK we're releasing a Beta release so we can receive feedback and iterate on this release.

#### Highlights

* [Runtime Style API](https://github.com/mapbox/mapbox-gl-native/issues/5610)
* [Earcut](https://github.com/mapbox/mapbox-gl-native/pull/2444)
* [SurfaceView](https://github.com/mapbox/mapbox-gl-native/issues/5000)

#### Usefull links

* [Release branch](https://github.com/mapbox/mapbox-gl-native/tree/release-android-4.2.0-beta.1)
* [CHANGELOG](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)

#### TODO list:
- [x] Create release branch
- [x] Change Version Name to `4.2.0-beta.1` in [`gradle.properties`](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/gradle.properties#L2)
- [x] Publish `4.2.0-beta.1` artifact to Maven Central
- [x] Updating Mapbox.com JavaDoc Documentation
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Tag `android-v4.2.0-beta.1` in GitHub
- [x] Tweet release -> https://twitter.com/Mapbox/status/763104598248792068
- [x] Change Version Name _BACK to SNAPSHOT after release and release branch merge_ to support daily development.  In this case set to  `4.2.0-SNAPSHOT` in [`gradle.properties`](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/gradle.properties#L2)
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.2.0-beta.1` and release on Google Play -> https://github.com/mapbox/mapbox-android-demo/issues/119

/cc @mapbox/mobile @mapbox/support @mapbox/sales @mapbox/communications

**Comment by bleege** [comment]
Capturing chat with @tobrun this afternoon about the status of this release.  All that remains is for the Demo App to be updated which @cammace is currently working on today.  For more information please see --> https://github.com/mapbox/mapbox-android-demo/issues/119
