### ISSUE TITLE
Release Android v4.2.0-beta.2

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6155]
Following `v4.2.0-beta.1` released on August 6th, we're now releasing `v4.2.0-beta.2` of the Mapbox Android SDK, that includes new features and numerous bugfixes. To help us ship a great release, please do [report any issues](https://github.com/mapbox/mapbox-gl-native/issues/new) you find using the SDK.

#### Highlights

This release brings major features that you can start testing and implementing today in your apps:

* Runtime Style API https://github.com/mapbox/mapbox-gl-native/issues/5610
* Query rendered features https://github.com/mapbox/mapbox-gl-native/issues/5869
* Clustering https://github.com/mapbox/mapbox-gl-native/issues/5852
* Integrated support for [Mapbox Android Services](https://www.mapbox.com/android-sdk/#mapbox_android_services)
* Map view rendered with `SurfaceView` https://github.com/mapbox/mapbox-gl-native/issues/5000
* Offline improvements:
  - Enable external storage to host the tiles database https://github.com/mapbox/mapbox-gl-native/issues/5589
  - Stop delivering status updates when offline download is canceled https://github.com/mapbox/mapbox-gl-native/issues/5538
  - Update SQLite schema with WAL journal mode and normal sync https://github.com/mapbox/mapbox-gl-native/pull/5796
  - Check for network connectivity before requesting resources https://github.com/mapbox/mapbox-gl-native/pull/6123

Full Changelog and known issues: https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aopen+is%3Aissue+milestone%3Aandroid-v4.2.0

#### TODO list for making this happen @zugaldia

- [x] Create release branch
- [x] Change version name to `4.2.0-beta.2` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Publish `4.2.0-beta.2` artifact to Maven Central
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Change version name back to `4.2.0-SNAPSHOT` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Merge `release-android-v4.2.0-beta.2` back into `master`
- [x] Create and tag `android-v4.2.0-beta.2` release on GitHub
- [x] Update JavaDoc Documentation @cammace 
- [ ] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.2.0-beta.2` and release on Google Play @cammace 
- [x] Tweet release announcement @DScientific @cammace 

/cc @mapbox/mobile @mapbox/support

**Comment by zugaldia** [comment]
@cammace @DScientific Over to you.

**Comment by cammace** [comment]
[Tweet's out](https://twitter.com/Mapbox/status/768897723474903041) and release of the demo app has been ticketed [seperately here](https://github.com/mapbox/mapbox-android-demo/issues/132).
