### ISSUE TITLE
Release Android v4.2.0-beta.3

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6418]
Following `v4.2.0-beta.2` released on August 25th, we're now releasing `v4.2.0-beta.3` of the Mapbox Android SDK. This release includes new features and bugfixes, and it's intended for development and testing purposes.

To help us ship a great release, please do report any issues you find in [the issue tracker](https://github.com/mapbox/mapbox-gl-native/issues/new).

#### Highlights

This release brings major new features:

* Runtime Style API https://github.com/mapbox/mapbox-gl-native/issues/5610
* Query rendered features https://github.com/mapbox/mapbox-gl-native/issues/5869
* Clustering https://github.com/mapbox/mapbox-gl-native/issues/5852
* Integrated support for [Mapbox Android Services](https://www.mapbox.com/android-sdk/#mapbox_android_services)
* Map view rendered with `SurfaceView` for improved performance https://github.com/mapbox/mapbox-gl-native/issues/5000
* Offline improvements:
  - Enable external storage to host the tiles database https://github.com/mapbox/mapbox-gl-native/issues/5589
  - Stop delivering status updates when offline download is canceled https://github.com/mapbox/mapbox-gl-native/issues/5538
  - Check for network connectivity before requesting resources https://github.com/mapbox/mapbox-gl-native/pull/6123

Full changelog and known issues: https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aopen+is%3Aissue+milestone%3Aandroid-v4.2.0

#### TODO list for making this happen @zugaldia

- [x] Create release branch
- [x] Change version name to `4.2.0-beta.3` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Publish `4.2.0-beta.3` artifact to Maven Central
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Change version name back to `4.2.0-SNAPSHOT` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Merge `release-android-v4.2.0-beta.3` back into `master`
- [x] Create and tag `android-v4.2.0-beta.3` release on GitHub
- [x] Update JavaDoc Documentation @cammace 
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.2.0-beta.3` and release on Google Play @cammace 
- [x] Tweet release announcement @DScientific @cammace 

/cc @mapbox/mobile @mapbox/support

**Comment by zugaldia** [comment]
`beta.3` published and [available on Maven Central](https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/4.2.0-beta.3/). Over to you @cammace .

**Comment by cammace** [comment]
Published new version of demo app to Play Store, should show up in a few hours. Closing release 🎫!!

**Comment by zugaldia** [comment]
Got the update last night 🎉 

![screenshot_20160922-091935](https://cloud.githubusercontent.com/assets/6964/18749664/f3b5f6a6-80a5-11e6-80e8-65c8bb0583ec.png)
