### ISSUE TITLE
Rework Android make targets

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6697]
Our current set of make targets have grown naturally over time, time to clean these up, streamline naming and introduce some usefull new ones:
### compile

make android-lib-{abi} (**same**, compiles .so file for a specific abi)
make android (**same**, compiles arm-v7 abi and compiles Android test app)
make android-core-test (**new**, todo #5456, only compile if needed)
make android-ui-test (**rename**, only compiles 2 test apk for firebase on bitrise, no native build?)

### run

make run-android (**new**, make android + install/run apk on device)
make run-android-core-test (**new**, todo #5456)
make run-android-unit-test (**rename**, unit tests on development machine)
make run-android-ui-test (**new**, instrumentation tests on device)

### generate
make style-code-android (**same**, remains for parity with other bindings)
make test-code-android (**rename**, replaces current android-generate-test)

## TODO:
 - [x] make android-ui-test (rename)
 - [x] make run-android (add)
 - [x] make run-android-unit-test (rename)
 - [x] make-run-android-ui-test (new)
 - [x] make test-code-android (rename)

cc @mapbox/android

**Comment by tobrun** [comment]
Other possible side targets we could consider:
 - ndk-stack
 - adb device management
 - pull offline database from rooted device
 - code coverage
 - javadoc
 - release?

**Comment by zugaldia** [comment]
Love it. I'm missing `apackage` from the list, any plans for it?

**Comment by tobrun** [comment]
I missed that one, where is that name `apackage` coming from?
I'm personally not a big fan of the naming.

**Comment by zugaldia** [comment]
@tobrun Not sure either, probably is short for "android package", feel free to rename it (remember this is the target used in `bitrise.yml` so that needs to be updated too).

**Comment by tobrun** [comment]
@zugaldia the apackage seems to be the `xpackage`  convention across platforms. Eg. iOS has ipackage. I'm going to keep this name for consistency.

**Comment by tobrun** [comment]
Final list of make configs is found in the [PR](https://github.com/mapbox/mapbox-gl-native/pull/6958#issue-187973534).
