### ISSUE TITLE
Release Android v4.2.0-beta.4

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6812]
Following `v4.2.0-beta.3` released on September 21st, we're now releasing `v4.2.0-beta.4` of the Mapbox Android SDK. This release includes new features and bugfixes, and it's intended for development and testing purposes.

Note that this is the first release in the `v4.2.0` series that comes with no remaining tickets open in [its milestone](https://github.com/mapbox/mapbox-gl-native/milestone/38). This beta can therefore be considered the first release candidate for `v4.2.0` of the Android SDK.

To help us ship a great release, please do report any issues you find in [the issue tracker](https://github.com/mapbox/mapbox-gl-native/issues/new).

#### Highlights

This release brings major new features:

* Runtime Style API https://github.com/mapbox/mapbox-gl-native/issues/5610
* Query rendered features (including by source) https://github.com/mapbox/mapbox-gl-native/issues/5869
* Clustering https://github.com/mapbox/mapbox-gl-native/issues/5852
* Integrated support for [Mapbox Android Services](https://www.mapbox.com/android-sdk/#mapbox_android_services)
* Map view rendered with `SurfaceView` for improved performance https://github.com/mapbox/mapbox-gl-native/issues/5000
* Decreased logging for release builds https://github.com/mapbox/mapbox-gl-native/pull/6787
* Offline improvements:
  - Enable external storage to host the tiles database https://github.com/mapbox/mapbox-gl-native/issues/5589
  - Stop delivering status updates when offline download is canceled https://github.com/mapbox/mapbox-gl-native/issues/5538
  - Check for network connectivity before requesting resources https://github.com/mapbox/mapbox-gl-native/pull/6123
  - setConnected method to manually set a connected flag https://github.com/mapbox/mapbox-gl-native/pull/6618

Full changelog and known issues: https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aopen+is%3Aissue+milestone%3Aandroid-v4.2.0

#### TODO list for making this happen @zugaldia

- [x] Create release branch `release-android-v4.2.0`
- [x] Change version name to `4.2.0-beta.4` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Publish `4.2.0-beta.4` artifact to Maven Central
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Change version name back to `4.2.0-SNAPSHOT` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Create and tag `android-v4.2.0-beta.4` release on GitHub
- [x] Update JavaDoc Documentation @cammace 
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.2.0-beta.4` and release on Google Play @cammace 
- [x] Tweet release announcement @DScientific @cammace 

/cc @mapbox/mobile @mapbox/support

**Comment by zugaldia** [comment]
@cammace : Over to you - https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/4.2.0-beta.4/.

**Comment by cammace** [comment]
Published beta.4 of the demo app to play store. Should be live a few hours. Release of `4.2.0-beta.4` is now complete 🎉
