### ISSUE TITLE
Release Android v4.2.0

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#7428]
Following `v4.2.0-beta.5` released on November 14th, we're now releasing the final `4.2.0` of the Mapbox Android SDK. This release includes new features and bug fixes, and it's intended for production use.

This is the final release in the `v4.2.0` series that comes with no remaining tickets open in [its milestone](https://github.com/mapbox/mapbox-gl-native/milestone/38). This release can then be considered the final release in the `v4.2.0` series.

To help us continue shipping excellent, stable releases, please do report any issues you find in [the issue tracker](https://github.com/mapbox/mapbox-gl-native/issues/new).

#### Highlights

This release brings major new features:

- Runtime Style API https://github.com/mapbox/mapbox-gl-native/issues/5610
- Query rendered features (including by source) https://github.com/mapbox/mapbox-gl-native/issues/5869
- Clustering https://github.com/mapbox/mapbox-gl-native/issues/5852
- Integrated support for [Mapbox Android Services](https://www.mapbox.com/android-sdk/#mapbox_android_services)
- Map view rendered with `SurfaceView` for improved performance https://github.com/mapbox/mapbox-gl-native/issues/5000
- Decreased logging for release builds https://github.com/mapbox/mapbox-gl-native/pull/6787
- Offline improvements:
  - Enable external storage to host the tiles database https://github.com/mapbox/mapbox-gl-native/issues/5589
  - Stop delivering status updates when offline download is canceled https://github.com/mapbox/mapbox-gl-native/issues/5538
  - Check for network connectivity before requesting resources https://github.com/mapbox/mapbox-gl-native/pull/6123
  - setConnected method to manually set a connected flag https://github.com/mapbox/mapbox-gl-native/pull/6618

Full changelog and known issues: https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aopen+is%3Aissue+milestone%3Aandroid-v4.2.0

#### TODO list for making this happen

- [x] Change version name to `4.2.0` in `/platform/android/MapboxGLAndroidSDK/gradle.properties` @cammace
- [x] Publish `4.2.0` artifact to Maven Central @cammace
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md) @cammace
- [x] Change version name back to `5.0.0-SNAPSHOT` in `/platform/android/MapboxGLAndroidSDK/gradle.properties` @cammace
- [x] Create and tag `android-v4.2.0` release on GitHub @cammace
- [x] Update JavaDoc Documentation @cammace 
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.2.0` and release on Google Play @cammace 
- [x] ~Tweet release announcement @DScientific @cammace~

/cc @mapbox/mobile @mapbox/support @mapbox/sales

**Comment by cammace** [comment]
New version of the [Demp app](https://github.com/mapbox/mapbox-android-demo) has been released to the Play Store. Closing!
