### ISSUE TITLE
Release Android v4.2.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7519]
Following the v4.2.0 released this month, we're now releasing a 4.2.1 bugfix release that solves issues reported by the community. A short term goal for @mapbox/android is to release more often so we  enable our users to iterate faster on the SDK.

### Highlights
This update brings the following improvements:
- Gesture handling bugs:
  - reverse fling issue when tilted
  - rotation gesture are hard to trigger issue
- Stability improvements (NullPointerException on TrackingSettings)
- Continuous integration improvements (symbolicating native stacktraces)
- Resolving density dependent margins from attributes correctly
- Usage of LocalBroadcastReceiver

### TODO list for making this happen
- [x] Change version name to `4.2.1` in `/platform/android/MapboxGLAndroidSDK/gradle.properties` @tobrun
- [x] Publish `4.2.1` artifact to Maven Central @tobrun
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md) @tobrun -> #7520 
- [x] Create and tag `android-v4.2.1` release on GitHub @tobrun
- [x] Update JavaDoc Documentation and mapbox.com @tobrun 
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.2.1` and release on Google Play @tobrun 

/cc @mapbox/mobile @mapbox/support @mapbox/sales

**Comment by tobrun** [comment]
I have been hitting some bumps getting the update released. I'm able to [build](https://www.bitrise.io/build/c0a61c9bb41814d1) without errors, upload the artifact to the staging repository and go through the default steps of releasing. The issue is that the v4.2.0 doesn't show up on [maven central](http://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/). It normally takes about 20 minutes while I have waited/retried the whole day. I'm going to give it a couple more hours. If it hasn't been fixed in the morning I will be contact support.

**Comment by tobrun** [comment]
Been looking at the issue tracker of sonatype and seeing similar reports of the issue shown above. All these tickets point to [this](https://issues.sonatype.org/browse/MVNCENTRAL-1433) as being the source of the issue. Capturing from that issue: 

> We experienced a setback in our hardware upgrades yesterday evening, which has once again blocked up syncs. I'm currently working on getting repo1.maven.org caught up on all of yesterday's published artifacts using alternate storage.

**Comment by tobrun** [comment]
Issues seem to been resolved, release is now available [here](http://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/).

**Comment by cammace** [comment]
Good to close this one now that 4.2.1 is out the 🚪 @tobrun?

**Comment by tobrun** [comment]
Still waiting on resolving:
 - [ ]  Update Mapbox Demo App to use 4.2.1 and release on Google Play @tobrun

Will close after that is completed.

**Comment by zugaldia** [comment]
@tobrun Please check your inbox, your Play invitation had expired but I just reissued it.

**Comment by tobrun** [comment]
Demo has been released! Closing
