### ISSUE TITLE
Release Android v4.2.2

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7827]
Following the v4.2.1 release last month, we're now releasing 4.2.2 that solves multiple issues reported by the community. This release fits in our continued effort of pushing out releases more often.

#### TODO list:
- [x] Change Version Name to `4.2.2` in gradle.properties.
- [x] Publish `4.2.2` artifact to Maven Central
- [x] Updating Mapbox.com JavaDoc Documentation
- [x] Update CHANGELOG.md
- [x] Tag `android-v4.2.2` in GitHub
- [x] Close Milestone `android-v4.2.2` in GitHub
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.2.2` and release on Google Play
- [x] Update Twitter Fabric

#### Related information:
Full Change Log [here](https://github.com/mapbox/mapbox-gl-native/blob/release-android-v4.2.2/platform/android/CHANGELOG.md)
Release Branch [here](https://github.com/mapbox/mapbox-gl-native/tree/release-android-v4.2.2)

/cc @mapbox/android

**Comment by klblk** [comment]
please add #7190 fix to 4.2.2

**Comment by zugaldia** [comment]
@klblk Sorry https://github.com/mapbox/mapbox-gl-native/pull/7190 didn't make to `4.2.2`. Rest assured though it'll make it to the next release, likely `5.0.0`.
