### ISSUE TITLE
Release Android v5.0.0-beta.1

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#8051]
In preparation for release `v5.0.0` of the Mapbox Android SDK, we're releasing today the first beta (`v5.0.0-beta.1`) in the `5.x` series. This release brings major features and numerous bug fixes, including breaking API changes. The main feature included with this release is support for [data-driven styles](https://www.mapbox.com/help/gl-dds-ref/).

To update your app from `4.x` to `5.0` please check and contribute to our [migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update).

Please note that this is a pre-release version intended to gather early feedback on the new APIs and to detect any potential issues ([you can report them here](https://github.com/mapbox/mapbox-gl-native/issues/new)). This release is not intended for production apps.

### Highlights

* Support for data-driven styles [#7752](https://github.com/mapbox/mapbox-gl-native/pull/7752)
* Consistent double tap zoom acceleration [#7514](https://github.com/mapbox/mapbox-gl-native/issues/7514)
* Cleanup inconsistencies `float` vs `double` [#4445](https://github.com/mapbox/mapbox-gl-native/issues/4445)
* Add `mapbox_` prefix to attributes [#6482](https://github.com/mapbox/mapbox-gl-native/issues/6482)
* Update LOST to 2.0.0 [#6573](https://github.com/mapbox/mapbox-gl-native/issues/6537)
* MAS submodules (geojson, telemetry) are now smaller to reduce the overall method count [#7642](https://github.com/mapbox/mapbox-gl-native/pull/7642)
* Support for Android Nougat [#5910](5910-move-listener-logic-for-nougat)
  - Move location listening logic to onStart/onStop Activity lifecylce methods
* Removal of `accessToken` on `MapView` and `MapboxMap` [#5621](https://github.com/mapbox/mapbox-gl-native/issues/5621)
* Introduction of new make targets [#5940](https://github.com/mapbox/mapbox-gl-native/issues/5940)
  - Targets for testing, running and using external tools directly from the command line
* Cleanup Gradle files [#6009](https://github.com/mapbox/mapbox-gl-native/issues/6009)
  - Introducing single purpose `.gradle` files
* Checkstyle integration [#7442](https://github.com/mapbox/mapbox-gl-native/pull/7442)
* Transform refactor [#6532](https://github.com/mapbox/mapbox-gl-native/issues/6532)
  - All camera related code is moved to a dedicated transform class cfr. core architecture
* Encapsulate Gestures [#6557](https://github.com/mapbox/mapbox-gl-native/issues/6557)
  - All gesture event code is encapsulated in `MapGestureDetector`
  - All key event code is encapsulated in `MapKeyListener`
* Transparent background for `MyLocationView` [#7116](https://github.com/mapbox/mapbox-gl-native/issues/7116)
* Update documentation on generate sanity tests [#7147](https://github.com/mapbox/mapbox-gl-native/issues/7147)
* Update documentation on style templates [#7157](https://github.com/mapbox/mapbox-gl-native/issues/7157)
* `NullPointerException` during save instance state [#7157](https://github.com/mapbox/mapbox-gl-native/issues/7157)
* Move management style to core [#7275](https://github.com/mapbox/mapbox-gl-native/issues/7275)
* `OnCameraChange` not called for the final position of animation bug [#7350](https://github.com/mapbox/mapbox-gl-native/issues/7350)
* `MapboxAccountManager` refactor [#6534](https://github.com/mapbox/mapbox-gl-native/issues/6534)
  - Consolidating the location where tokens are set
  - Rename to reflect the increased responsibilities introduced in prior releases
* AnnotationManager refactor [#6067](https://github.com/mapbox/mapbox-gl-native/issues/6067)
  - Extracting all business logic related to annotations into a separate class cfr. to core and the iOS codebase
* Gesture handling bugs
  - Avoid calls to onFling when while pinch zooming [#7666](https://github.com/mapbox/mapbox-gl-native/issues/7666)
* Support for style-wide transition animation duration and delay [#6779](https://github.com/mapbox/mapbox-gl-native/issues/6779)
* Support for all animated camera changes to configure dismissing tracking modes [#7854](https://github.com/mapbox/mapbox-gl-native/issues/7854)
* `LatLng` objects produced by the SDK are wrapped by default [#4522](https://github.com/mapbox/mapbox-gl-native/issues/4522)

Full changelog and known issues: https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aopen+is%3Aissue+milestone%3Aandroid-v5.0.0

### TODO list for making this happen @zugaldia

- [x] Create release branch
- [x] Change version name to `5.0.0-beta.1` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Publish `5.0.0-beta.1` artifact to Maven Central
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Change version name back to `5.0.0-SNAPSHOT` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Merge `release-android-v5.0.0-beta.1` back into `master`
- [x] Create and tag `android-v5.0.0-beta.1` release on GitHub
- [x] Update JavaDoc Documentation @cammace 
- [ ] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `5.0.0-beta.1` and release on Google Play @cammace 
- [ ] Tweet release announcement @cammace 

/cc @mapbox/mobile @mapbox/support

**Comment by zugaldia** [comment]
Please note that due to an ongoing issue with our CI https://github.com/mapbox/mapbox-gl-native/issues/7733, this build does not include all architectures (`lib-mips` and `lib-x86-64` are missing, `lib-arm-v5`, `lib-arm-v7`, `lib-arm-v8`, `lib-x86` are included).

**Comment by zugaldia** [comment]
Artifacts are now [available on Maven](http://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/5.0.0-beta.1/), over to you @cammace .

**Comment by cammace** [comment]
Tweet going out later today and updating of the demo app is being tracked in https://github.com/mapbox/mapbox-android-demo/issues/222. Closing

**Comment by nitrag** [comment]
Congratulations on the beta and thank you! Long awaited!

Can you please publish the docs? I was told they would live [here](https://www.mapbox.com/android-sdk/api/5.0.0-beta.1) but all I see is a lovely 404 page. 😉

**Comment by cammace** [comment]
Hey @nitrag, an internal issue was causing the documentation to not get published. It has now been fixed and the documentation can be viewed [here](https://www.mapbox.com/android-sdk/api/5.0.0-beta.1/)
