### ISSUE TITLE
Release iOS SDK v3.5.0

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#8454]
Following v3.5.0-rc.1 released in March 15th, we are now releasing v3.5.0 final of Mapbox iOS SDK.

# TODO

## Version the packages
- [ ] Update the version in the podspec.
- [ ] Update the CHANGELOG.md for the release.
- [ ] Create a pull request with these changes and have it approved/merged.
- [ ] Create a tag ios-vX.Y.Z.
- [ ] git push origin ios-vX.Y.Z

## Build and release

- [ ] Run make ideploy. 
- [ ] Upload to s3 (if you've run mbx auth above).
- [ ] Test that downloads from s3 work.
- [ ] Make a new Github release draft and upload all of the compressed release files to the Github release.
- [ ] Go to https://github.com/mapbox/mapbox-gl-native/releases to find the draft, confirm that it is valid, and add notes from the changelog.
- [ ] Publish draft.

### cocoapods

- [ ] Run pod trunk push platform/ios/Mapbox-iOS-SDK.podspec.

cc @mapbox/mobile @mapbox/support

**Comment by boundsj** [comment]
Thanks for making this ticket @fabian-guerra. I _think_ we can skip the translations step this time. cc @1ec5

**Comment by 1ec5** [comment]
Yes, we can skip the translation updates: no new translations have cropped up since I issued a call for them after beta 3.

**Comment by fabian-guerra** [comment]
Moving this for internal tracking.
