### ISSUE TITLE
Release Android v5.0.1

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#8501]
Release `v5.0.1` is the first patch release in the `5.x` series. This release addresses a shader precision issue that created a rendering problem on some devices.

### Highlights

* Use `highp` for color attributes [#8385](https://github.com/mapbox/mapbox-gl-native/issues/8385)

### TODO list for making this happen @zugaldia

- [x] Change version name to `5.0.1` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Publish `5.0.1` artifact to Maven Central
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Change version name back to `5.1.0-SNAPSHOT` in `/platform/android/MapboxGLAndroidSDK/gradle.properties`
- [x] Create and tag `android-v5.0.1` release on GitHub
- [x] Update JavaDoc Documentation @cammace 
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `5.0.1` and release on Google Play @cammace 
- [ ] Tweet release announcement @cammace 

/cc @mapbox/mobile @mapbox/support

**Comment by zugaldia** [comment]
The [5.0.1 artifact](http://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/5.0.1/) is now available on Maven Central.

**Comment by snowpong** [comment]
I've just tested the 5.0.1 release on my Mate 9 Pro and it fixes the rendering issues. See attached screenshots. The first one with the pink road and mostly white map is with 5.0.0 and the one that looks sane is 5.0.1. Gets a 👍 from me.

![mapbox 5 0 0 with outdoors](https://cloud.githubusercontent.com/assets/177436/24244312/99b8cca2-0fbe-11e7-8f2b-240fbe253b53.png)
![mapbox 5 0 1 with outdoors](https://cloud.githubusercontent.com/assets/177436/24244311/99b8b276-0fbe-11e7-8de6-ba00c78aa0e2.png)

**Comment by zugaldia** [comment]
@snowpong Thank you for checking and confirming. Your app is looking great by the way!

**Comment by brunoabinader** [comment]
@snowpong great to see you around here! 👋

**Comment by zugaldia** [comment]
The demo app using 5.0.1 has just been rolled out to production.

@cammace could you help with the remaining items on the list?
