### ISSUE TITLE
Release Android v5.0.2

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8623]
Release `v5.0.2` is the second patch release in the `5.x` series. This release adds binary shader caching, reverts touch interaction to the 4.x implementation, fixes MarkerView anchoring and a resource transform callback crash.

### Highlights

* Binary shader caching [#8604](https://github.com/mapbox/mapbox-gl-native/pull/8604)
* Fix resource transform callback [#8582](https://github.com/mapbox/mapbox-gl-native/pull/8582) in [#8586](https://github.com/mapbox/mapbox-gl-native/pull/8586)
* Correct anchoring when updating MarkerView Icon [#8519](https://github.com/mapbox/mapbox-gl-native/pull/8519) in [#8586](https://github.com/mapbox/mapbox-gl-native/pull/8586#issuecomment-290682710)
* Revert 5.x onTouch changes to 4.x [#8585](https://github.com/mapbox/mapbox-gl-native/pull/8585)

### TODO list for making this happen @tobrun

- [x] Change version name to `5.0.2` in `/platform/android/MapboxGLAndroidSDK/gradle.properties` -> https://github.com/mapbox/mapbox-gl-native/pull/8629
- [x] Publish `5.0.2` artifact to Maven Central -> http://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/5.0.2/
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md) -> https://github.com/mapbox/mapbox-gl-native/pull/8629
- [x] Change version name back to `5.1.0-SNAPSHOT` in `/platform/android/MapboxGLAndroidSDK/gradle.properties` -> https://github.com/mapbox/mapbox-gl-native/pull/8629
- [x] Create and tag `android-v5.0.2` release on GitHub -> https://github.com/mapbox/mapbox-gl-native/releases/tag/v5.0.2
- [x] Update JavaDoc Documentation @langsmith / @cammace   
- [x] Update documentation on mapbox.com Android install workflow @langsmith / @cammace   
- [x] Update documentation in /help repo @langsmith / @cammace   
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `5.0.2` and release on Google Play @langsmith / @cammace 
- [x] Tweet release announcement @langsmith / @cammace 

/cc @mapbox/mobile @mapbox/support

**Comment by jfirebaugh** [comment]
Note that https://github.com/mapbox/mapbox-gl-native/pull/8604 isn't merged yet.

**Comment by tobrun** [comment]
@langsmith can you work together with @cammace on the remaining items?

**Comment by langsmith** [comment]
Yep @tobrun. [Branch has been opened](https://github.com/mapbox/android-sdk/compare/updating-to-5.0.2?expand=1) and I'm already making updates.

**Comment by langsmith** [comment]
TODO list finished. Closing.
