### ISSUE TITLE
Release Android v5.1.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9564]
# Android v5.1.1
We are releasing a first patch release on top of the v5.1.0 version of the Android SDK. This release focuses on improved stability  and support for clickable Polygons and Polylines through `OnPolylineClickListener` and `OnPolygonClickListener`. Feel free to report any feedback you have on this release [here](https://github.com/mapbox/mapbox-gl-native/issues).

![ezgif com-video-to-gif 72](https://user-images.githubusercontent.com/2151639/28414568-926d74d4-6d4c-11e7-8104-f0a7c06ef125.gif)

## Changes since v5.1.0
* Work around Adreno 2xx bugs [#9573](https://github.com/mapbox/mapbox-gl-native/pull/9573)
* Rework attribution binding [#9433](https://github.com/mapbox/mapbox-gl-native/pull/9433)
* BackendScope changes [#9538](https://github.com/mapbox/mapbox-gl-native/pull/9538)
* Invisible MarkerView performance fix [#9420](https://github.com/mapbox/mapbox-gl-native/pull/9420)
* Polyline/Polygon click listeners [#9443](https://github.com/mapbox/mapbox-gl-native/pull/9443)
* Hit test Marker/MarkerViews [#9424](https://github.com/mapbox/mapbox-gl-native/pull/9424)
* Fine tune fling gesture [#9532](https://github.com/mapbox/mapbox-gl-native/pull/9532)
* Bump OkHttp 3.8.0, Android 7.x crashes [#9522](https://github.com/mapbox/mapbox-gl-native/pull/9522)
* MyLocationView tint fix [#9410](https://github.com/mapbox/mapbox-gl-native/pull/9410)
* VisibleRegion logic [#9428](https://github.com/mapbox/mapbox-gl-native/pull/9428)
* Validate motion event [#9434](https://github.com/mapbox/mapbox-gl-native/pull/9434)
* Add French localization [#9545](https://github.com/mapbox/mapbox-gl-native/pull/9545)

## Todo

 - [x] Create release branch
 - [x] Update CHANGELOG.md 
 - [x] Change CircleCI config to build from release branch (android-release-all->deploy)
 - [x] Change version name to `5.1.1` in /platform/android/MapboxGLAndroidSDK/gradle.properties
 - [x] Publish `5.1.0` artifact to Maven Central
 - [x] Change version name to `5.2.0-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
 - [x] Change CircleCI config to build back from release/master branch
 - [x] Merge `release-android-v5.1.1` back into `release-ios-v3.6.0-android-v5.1.0`
 - [x] Create and tag `android-v5.1.1` release on GitHub 
 - [x] Update Javadoc documentation @langsmith 
 - [x] Update SDK version to `5.1.1` in `android-docs` repo's `constants.js` file @langsmith 
 - [x] Update Mapbox demo and wearable demo apps to use `5.1.1` and release on Google Play @langsmith 
 - [x] _If needed_ (check [change log](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CHANGELOG.md)), update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)
 - [x] Update version # in constants file in /help @langsmith
 - [x] Update version # in constants file in /www.mapbox.com @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support

**Comment by langsmith** [comment]
Closing 🎆 🎊
