### ISSUE TITLE
Release Android v5.1.2

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9683]
# Android v5.1.2
We are releasing the second patch release on top of the v5.1.0 version of the Android SDK. This release focuses on improved bug fixes and render stability. Feel free to report any feedback you have on this release [here](https://github.com/mapbox/mapbox-gl-native/issues).

## Changes since v5.1.1

* Disable program caching on Ardreno GPU 3xx, 4xx and 5xx [#9625](https://github.com/mapbox/mapbox-gl-native/pull/9625)
* GeoJSON proguard issue [#9577](https://github.com/mapbox/mapbox-gl-native/pull/9577)
* Harden click events of shape annotations [#9585](https://github.com/mapbox/mapbox-gl-native/pull/9585)
* Validate Marker before opening InfoWindow [#9586](https://github.com/mapbox/mapbox-gl-native/pull/9586)
* Fix added to map check [#9602](https://github.com/mapbox/mapbox-gl-native/pull/9602)
* Don't query shape annotations if none were added [#9606](https://github.com/mapbox/mapbox-gl-native/pull/9606)
* Fix compass direction [#9632](https://github.com/mapbox/mapbox-gl-native/pull/9632)
* Remove preview image integration [#9657](https://github.com/mapbox/mapbox-gl-native/pull/9657)
* Try/catch initialization of telemetry [#9658](https://github.com/mapbox/mapbox-gl-native/pull/9658)
* Fix typo OnCameraMoveStartedListener [#9664](https://github.com/mapbox/mapbox-gl-native/pull/9664)
* Bump MAS dependency to 2.2.0 [#9671](https://github.com/mapbox/mapbox-gl-native/pull/9671)

## Todo

 - [x] Create release branch
 - [x] Update CHANGELOG.md 
 - [x] Change CircleCI config to build from release branch (android-release-all->deploy)
 - [x] Change version name to `5.1.2` in /platform/android/MapboxGLAndroidSDK/gradle.properties
 - [x] Publish `5.1.2` artifact to Maven Central
 - [x] Tag `android-v5.1.2` 
 - [x] Change version name to `5.1.3-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
 - [x] Change CircleCI config to build back from release branch
 - [x] Merge `release-android-v5.1.2` back into `release-ios-v3.6.0-android-v5.1.0`
 - [x] Update Javadoc documentation @langsmith 
 - [x] Update SDK version to `5.1.2` in `android-docs` repo's `constants.js` file @langsmith 
 - [x] Update Mapbox demo and wearable demo apps to use `5.1.2` and release on Google Play @langsmith 
 - [x] ~~_If needed_ (check [change log](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CHANGELOG.md)), update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
 - [x] Update version # in `config` files in /help @langsmith
 - [x] Update version # in constants file in /www.mapbox.com @langsmith
- [x] Notify Fabric @langsmith
- [x] Create new tag in demo app repo @langsmith
- [x] Release new version of Android demo app on Play Store

--------------------------
/cc @mapbox/mobile @mapbox/support

**Comment by langsmith** [comment]
Done 🎊 🎆

**Comment by ragaisis** [comment]
master branch changelog has info only about 5.1.0 and no info about 5.1.2. I think it could be good practice after releasing new version update at least master branch changelog. IMHO other developers are looking there for recent changes

**Comment by tobrun** [comment]
correct, will cherry pick them to master.
