### ISSUE TITLE
Release Android v5.1.3

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9800]
# Android v5.1.3
We are releasing the third patch release on top of the v5.1.0 version of the Android SDK. This release adds the bugfixes mentioned below. Feel free to report any feedback you have on this release [here](https://github.com/mapbox/mapbox-gl-native/issues).

## Changes since v5.1.2
* Use separate attribute component for line normals [#9753](https://github.com/mapbox/mapbox-gl-native/pull/9753)
* Track state of initial overlain views margins [#9391](https://github.com/mapbox/mapbox-gl-native/pull/9391)
 * Compability for Samsung devices forcing 3-4 array vector length [#9746](https://github.com/mapbox/mapbox-gl-native/pull/9746)
 * Smallest LatLngBounds when visible region crosses dateline [#9747](https://github.com/mapbox/mapbox-gl-native/pull/9747)
 * Readd ProjectMeters [#9766](https://github.com/mapbox/mapbox-gl-native/pull/9766)
 * Enable location change animation of MyLocationView by default [#9779](https://github.com/mapbox/mapbox-gl-native/pull/9779)
 * Avoid IndexOutOfBoundsException when destroying map object [#9789](https://github.com/mapbox/mapbox-gl-native/pull/9789)
 * MAS 2.2.1 [#9796](https://github.com/mapbox/mapbox-gl-native/pull/9796)

## Todo

- [x] Create release branch
- [x] Update CHANGELOG.md 
- [x] Change CircleCI config to build from release branch (android-release-all->deploy)
- [x] Change version name to `5.1.3` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Publish `5.1.3` artifact to Maven Central
- [x] Tag `android-v5.1.3` 
- [x] Change version name to `5.1.4-SNAPSHOT` in /platform/android/MapboxGLAndroidSDK/gradle.properties
- [x] Change CircleCI config to build back from release branch
- [x] Merge `release-android-v5.1.3` back into `release-ios-v3.6.0-android-v5.1.0`
- [x] Update Javadoc documentation @langsmith 
- [x] Update SDK version to `5.1.3` in `android-docs` repo's `constants.js` file @langsmith 
- [x] Update Mapbox demo and wearable demo apps to use `5.1.3` and release on Google Play @langsmith 
- [x] ~~update the style specification’s SDK support tables @langsmith [note](https://github.com/mapbox/mapbox-gl-native/issues/9404#issuecomment-312375807)~~
- [x] Update version # in `config` files in /help @langsmith
- [x] Update version # in `src > constants.js` file in /www.mapbox.com @langsmith
- [x] Notify Fabric @langsmith
- [x] Create new tag in demo app repo @langsmith
- [x] Release new version of Android demo app on Play Store @langsmith

--------------------------
/cc @mapbox/mobile @mapbox/support

**Comment by langsmith** [comment]
Will do Fabric stuff next week in DC

cc @zugaldia

**Comment by langsmith** [comment]
@tobrun Remaining two checkboxes are yours...
